import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { ALIAS_CONTRACT_VERSION, ALIAS_RESOLUTION_POLICY, ALIAS_SET_CONTRACT_VERSION, CANONICAL_IDENTITY_CONTRACT_VERSION, MAX_ALIASES, issueResultMappingDecision, normalizeCanonicalIdentity, resolveProviderAlias, validateAliasSet } from '../src/domain/intelligence/canonical-identity.ts';
import { DEDUPLICATION_POLICY, MAX_OBSERVATION_FACTS, OBSERVATION_SCOPE_VERSION, classifyObservation, compareObservationOrder } from '../src/domain/intelligence/observation-deduplication.ts';
import { PAYLOAD_HASH_POLICY, verifyPayloadHash } from '../src/domain/intelligence/payload-hash.ts';

const at = '2026-08-28T01:00:00.000Z', boundary = '2026-08-28T02:00:00.000Z', after = '2026-08-28T03:00:00.000Z';
const hash = (byte) => `sha256:${byte.repeat(64)}`;
const value = (result) => { assert.equal(result.ok, true, result.ok ? undefined : `${result.error.code}: ${result.error.path}`); return result.value; };
const error = (result, code) => { assert.equal(result.ok, false); assert.equal(result.error.code, code); assert.ok(Object.isFrozen(result.error)); return result.error; };

function identity(overrides = {}) { return { contractVersion: CANONICAL_IDENTITY_CONTRACT_VERSION, entityType: 'event', canonicalId: 'event:opaque-1', version: 'identity/2', evidenceRefs: ['evidence/event'], sportId: 'sport:opaque-1', competitionId: 'competition:opaque-1', eventStartAt: boundary, participants: [{ participantId: 'participant:opaque-a', roleId: 'role:home-1', role: 'home', roleVersion: '1', evidenceRefs: ['e/a'] }, { participantId: 'participant:opaque-b', roleId: 'role:away-1', role: 'away', roleVersion: '1', evidenceRefs: ['e/b'] }], ...overrides }; }
function alias(status = 'resolved', overrides = {}) { const state = { resolved: { canonicalId: 'event:opaque-1' }, unresolved: {}, ambiguous: { viableCandidateRefs: ['candidate/a', 'candidate/b'] }, quarantined: { quarantineReason: 'manual_identity_review' }, superseded: { historicalCanonicalId: 'event:opaque-old', supersededByAliasRef: 'alias/new', supersessionReason: 'provider_rekey' } }[status]; return { contractVersion: ALIAS_CONTRACT_VERSION, aliasRef: 'alias/current', entityType: 'event', sourceId: 'source_a', providerRef: 'provider/a', externalKey: 'event/77', sportId: 'sport:opaque-1', competitionId: 'competition:opaque-1', eventStartAt: boundary, effectiveFrom: at, status, evidenceRefs: ['evidence/alias'], version: 'alias/2', ...state, ...overrides }; }
function candidate(id = 'event:opaque-1', ref = 'candidate/one', overrides = {}) { return { candidateRef: ref, canonicalId: id, entityType: 'event', sourceId: 'source_a', providerRef: 'provider/a', externalKey: 'event/77', sportId: 'sport:opaque-1', competitionId: 'competition:opaque-1', eventStartAt: boundary, evidenceRefs: [`evidence/${ref}`], evidenceKind: 'exact_source_key', ...overrides }; }
const set = (...aliases) => ({ contractVersion: ALIAS_SET_CONTRACT_VERSION, aliases });
const resolve = (aliasSet, candidates, asOf = at) => resolveProviderAlias({ aliasSet, candidates, asOf, policy: ALIAS_RESOLUTION_POLICY });

test('entity-tagged opaque IDs enforce runtime type separation and immutable role IDs', () => { const result = value(normalizeCanonicalIdentity(identity())); assert.ok(Object.isFrozen(result.participants[0])); for (const [field, wrong] of [['canonicalId', 'participant:opaque-1'], ['sportId', 'competition:opaque-1'], ['competitionId', 'sport:opaque-1']]) error(normalizeCanonicalIdentity(identity({ [field]: wrong })), 'invalid_entity_id'); error(normalizeCanonicalIdentity(identity({ participants: [{ ...identity().participants[0], participantId: 'event:opaque-a' }, identity().participants[1]] })), 'invalid_entity_id'); error(normalizeCanonicalIdentity(identity({ participants: [{ ...identity().participants[0], roleId: 'participant:home-1' }, identity().participants[1]] })), 'invalid_entity_id');
  for (const entity of [{ contractVersion: CANONICAL_IDENTITY_CONTRACT_VERSION, entityType: 'sport', canonicalId: 'sport:same', version: '1', evidenceRefs: ['e'] }, { contractVersion: CANONICAL_IDENTITY_CONTRACT_VERSION, entityType: 'competition', canonicalId: 'competition:same', sportId: 'sport:same', version: '1', evidenceRefs: ['e'] }, { contractVersion: CANONICAL_IDENTITY_CONTRACT_VERSION, entityType: 'participant', canonicalId: 'participant:same', sportId: 'sport:same', version: '1', evidenceRefs: ['e'] }]) assert.equal(normalizeCanonicalIdentity(entity).ok, true); });

test('singleton role semantics cannot be bypassed by distinct opaque role IDs', () => { const base = identity().participants; for (const role of ['home', 'away', 'draw']) { const participants = [{ ...base[0], role, roleId: `role:${role}-a` }, { ...base[1], role, roleId: `role:${role}-b` }]; const first = error(normalizeCanonicalIdentity(identity({ participants })), 'duplicate_role_semantic'); const second = error(normalizeCanonicalIdentity(identity({ participants: [...participants].reverse() })), 'duplicate_role_semantic'); assert.equal(first.path, '$.participants[1].role'); assert.equal(first.inputIndex, 1); assert.equal(second.path, first.path); assert.equal(second.inputIndex, first.inputIndex); assert.ok(Object.isFrozen(first)); }
  const competitors = [{ ...base[0], role: 'competitor', roleId: 'role:competitor-a' }, { ...base[1], role: 'competitor', roleId: 'role:competitor-b' }]; assert.equal(normalizeCanonicalIdentity(identity({ participants: competitors })).ok, true); assert.equal(normalizeCanonicalIdentity(identity({ participants: [...competitors].reverse() })).ok, true); });

function contextualAlias(entityType, overrides = {}) { const contexts = { sport: {}, competition: { sportId: 'sport:context' }, participant: { sportId: 'sport:context', competitionId: 'competition:context' }, event: { sportId: 'sport:context', competitionId: 'competition:context', eventStartAt: boundary } }; const result = alias('resolved', { entityType, canonicalId: `${entityType}:context` }); delete result.sportId; delete result.competitionId; delete result.eventStartAt; Object.assign(result, contexts[entityType], overrides); for (const key of ['sportId', 'competitionId', 'eventStartAt']) if (result[key] === undefined) delete result[key]; return result; }
function contextualCandidate(entityType, overrides = {}) { const contexts = { sport: {}, competition: { sportId: 'sport:context' }, participant: { sportId: 'sport:context', competitionId: 'competition:context' }, event: { sportId: 'sport:context', competitionId: 'competition:context', eventStartAt: boundary } }; const result = candidate(`${entityType}:context`, 'candidate/context', { entityType }); delete result.sportId; delete result.competitionId; delete result.eventStartAt; Object.assign(result, contexts[entityType], overrides); for (const key of ['sportId', 'competitionId', 'eventStartAt']) if (result[key] === undefined) delete result[key]; return result; }

test('aliases and candidates share the complete entity-context matrix', () => { for (const entityType of ['sport', 'competition', 'participant', 'event']) { const stored = contextualAlias(entityType); assert.equal(validateAliasSet(set(stored)).ok, true); assert.equal(value(resolve(set(stored), [contextualCandidate(entityType)])).status, 'resolved'); }
  const invalid = [{ type: 'sport', field: 'sportId', value: 'sport:x' }, { type: 'sport', field: 'competitionId', value: 'competition:x' }, { type: 'sport', field: 'eventStartAt', value: boundary }, { type: 'competition', field: 'sportId', value: undefined }, { type: 'competition', field: 'competitionId', value: 'competition:x' }, { type: 'competition', field: 'eventStartAt', value: boundary }, { type: 'participant', field: 'sportId', value: undefined }, { type: 'participant', field: 'eventStartAt', value: boundary }, { type: 'event', field: 'sportId', value: undefined }, { type: 'event', field: 'competitionId', value: undefined }, { type: 'event', field: 'eventStartAt', value: undefined }];
  for (const item of invalid) { const stored = contextualAlias(item.type, { [item.field]: item.value }); error(validateAliasSet(set(stored)), 'invalid_entity_context'); const validStored = contextualAlias(item.type); const badCandidate = contextualCandidate(item.type, { [item.field]: item.value }); error(resolve(set(validStored), [badCandidate]), 'invalid_entity_context'); }
  error(resolve(set(contextualAlias('event')), [contextualCandidate('participant')]), 'identity_conflict'); error(resolve(set(contextualAlias('event')), [contextualCandidate('event', { sportId: 'sport:other' })]), 'identity_conflict'); error(resolve(set(contextualAlias('event')), [contextualCandidate('event', { competitionId: 'competition:other' })]), 'identity_conflict'); error(resolve(set(contextualAlias('event')), [contextualCandidate('event', { eventStartAt: after })]), 'identity_conflict'); const participantWithoutCompetition = contextualAlias('participant', { competitionId: undefined }); error(resolve(set(participantWithoutCompetition), [contextualCandidate('participant')]), 'identity_conflict'); });

test('alias state machine accepts every coherent state and rejects every forbidden active/history field', () => { const valid = [alias('resolved'), alias('unresolved'), alias('ambiguous'), alias('quarantined'), alias('superseded', { effectiveTo: boundary })]; for (const item of valid) assert.equal(validateAliasSet(set(item.status === 'superseded' ? item : item)).ok, item.status !== 'superseded');
  const forbidden = { resolved: ['historicalCanonicalId', 'viableCandidateRefs', 'quarantineReason', 'supersededByAliasRef', 'supersessionReason'], unresolved: ['canonicalId', 'historicalCanonicalId', 'viableCandidateRefs', 'quarantineReason', 'supersededByAliasRef', 'supersessionReason'], ambiguous: ['canonicalId', 'historicalCanonicalId', 'quarantineReason', 'supersededByAliasRef', 'supersessionReason'], quarantined: ['canonicalId', 'historicalCanonicalId', 'supersededByAliasRef', 'supersessionReason'], superseded: ['canonicalId', 'viableCandidateRefs', 'quarantineReason'] };
  const samples = { canonicalId: 'event:x', historicalCanonicalId: 'event:x', viableCandidateRefs: ['candidate/a', 'candidate/b'], quarantineReason: 'review', supersededByAliasRef: 'alias/new', supersessionReason: 'reason' };
  for (const [status, fields] of Object.entries(forbidden)) for (const field of fields) { const item = alias(status, { [field]: samples[field] }); error(validateAliasSet(set(item)), 'invalid_alias_state'); }
  error(validateAliasSet(set(alias('resolved', { canonicalId: undefined }))), 'invalid_input'); error(validateAliasSet(set(alias('ambiguous', { viableCandidateRefs: ['candidate/a'] }))), 'invalid_alias_state'); error(validateAliasSet(set(alias('quarantined', { quarantineReason: undefined }))), 'invalid_input'); });

test('stored alias state and resolution result cannot contradict, including hidden winners', () => { const resolved = value(resolve(set(alias('resolved')), [candidate()])); assert.equal(resolved.status, 'resolved'); assert.equal(resolved.canonicalId, 'event:opaque-1'); error(resolve(set(alias('resolved')), [candidate('event:other')]), 'alias_state_contradiction'); error(resolve(set(alias('unresolved')), [candidate()]), 'alias_state_contradiction'); const unknown = value(resolve(set(alias('unresolved')), [])); assert.equal(unknown.status, 'unresolved'); assert.equal('canonicalId' in unknown, false);
  const ambiguousAlias = alias('ambiguous'); const candidates = [candidate('event:b', 'candidate/b'), candidate('event:a', 'candidate/a')]; const ambiguous = value(resolve(set(ambiguousAlias), candidates)); assert.equal(ambiguous.status, 'ambiguous'); assert.deepEqual(ambiguous.candidateRefs, ['candidate/a', 'candidate/b']); assert.equal('canonicalId' in ambiguous, false); error(resolve(set(ambiguousAlias), [candidate('event:a', 'candidate/a')]), 'alias_state_contradiction'); const quarantined = value(resolve(set(alias('quarantined')), [candidate()])); assert.equal(quarantined.status, 'quarantined'); assert.equal('canonicalId' in quarantined, false); });

test('alias-set validator enforces lifecycle uniqueness, scope, intervals and exact transitions', () => { error(validateAliasSet(set(alias('unresolved'), alias('unresolved'))), 'duplicate_alias_reference'); error(validateAliasSet(set(alias('unresolved'), alias('unresolved', { aliasRef: 'alias/b', sourceId: 'source_b', effectiveFrom: boundary }))), 'alias_scope_conflict'); error(validateAliasSet(set(alias('unresolved'), alias('unresolved', { aliasRef: 'alias/b' }))), 'overlapping_alias_interval');
  const old = alias('superseded', { effectiveTo: boundary }); const next = alias('resolved', { aliasRef: 'alias/new', effectiveFrom: boundary }); const lifecycle = value(validateAliasSet(set(old, next))); assert.equal(lifecycle.aliases.length, 2); assert.equal(value(resolve(set(old, next), [], at)).status, 'superseded'); assert.equal(value(resolve(set(old, next), [candidate()], boundary)).status, 'resolved'); error(validateAliasSet(set(alias('superseded', { effectiveTo: boundary, supersededByAliasRef: 'alias/missing' }))), 'missing_alias_successor'); error(validateAliasSet(set(alias('superseded', { effectiveTo: boundary, supersededByAliasRef: 'alias/current' }))), 'alias_supersession_cycle'); error(validateAliasSet(set(old, { ...next, effectiveFrom: after })), 'invalid_alias_transition'); });

test('alias-set limits are enforced before traversal', () => { const aliases = Array.from({ length: MAX_ALIASES + 1 }, (_, index) => alias('unresolved', { aliasRef: `alias/${index}`, effectiveFrom: new Date(Date.parse(at) + index * 60_000).toISOString(), effectiveTo: new Date(Date.parse(at) + (index + 1) * 60_000).toISOString() })); assert.equal(validateAliasSet(set(...aliases.slice(0, MAX_ALIASES))).ok, true); error(validateAliasSet(set(...aliases)), 'limit_exceeded'); });

function scope(overrides = {}) { return { contractVersion: OBSERVATION_SCOPE_VERSION, sportId: 'sport:opaque-1', competitionId: 'competition:opaque-1', eventId: 'event:opaque-1', marketId: 'market_h2h', outcomeIds: ['outcome_a', 'outcome_b'], identityContractVersion: CANONICAL_IDENTITY_CONTRACT_VERSION, ...overrides }; }
function fact(ref, overrides = {}) { return { contractVersion: 'observation-fact-v2', observationRef: ref, sourceEnvelopeRef: 'envelope/source-row-1', sourceId: 'source_a', providerRef: 'provider/a', scope: scope(), payloadHash: hash('a'), observedAt: at, receivedAt: at, ...overrides }; }
const classify = (incoming, existing = []) => classifyObservation({ incoming, existing, policy: DEDUPLICATION_POLICY });

test('observation scope requires all dimensions, tagged parents, unique canonical outcome order', () => { for (const field of ['sportId', 'competitionId', 'eventId', 'marketId', 'outcomeIds', 'identityContractVersion']) { const invalid = scope(); delete invalid[field]; error(classify(fact('obs/1', { scope: invalid })), field === 'outcomeIds' ? 'invalid_input' : field.endsWith('Id') ? 'invalid_identifier' : 'invalid_reference'); } error(classify(fact('obs/1', { scope: scope({ sportId: 'competition:same' }) })), 'invalid_entity_id'); error(classify(fact('obs/1', { scope: scope({ outcomeIds: ['outcome_a', 'outcome_a'] }) })), 'duplicate_outcome'); error(classify(fact('obs/1', { scope: scope({ outcomeIds: ['outcome_b', 'outcome_a'] }) })), 'noncanonical_outcome_order'); });

test('complete exact-fact tuple includes source envelope and every immutable scope dimension', () => { const original = fact('obs/1'); assert.equal(value(classify(fact('obs/reimport'), [original])).classification, 'exact_duplicate'); const variations = [{ sourceEnvelopeRef: 'envelope/other' }, { sourceId: 'source_b' }, { providerRef: 'provider/b' }, { scope: scope({ sportId: 'sport:other' }) }, { scope: scope({ competitionId: 'competition:other' }) }, { scope: scope({ eventId: 'event:other' }) }, { scope: scope({ marketId: 'market_line' }) }, { scope: scope({ outcomeIds: ['outcome_a', 'outcome_c'] }) }, { scope: scope({ identityContractVersion: 'identity/other' }) }, { observedAt: '2026-08-28T00:59:00.000Z' }, { receivedAt: '2026-08-28T01:01:00.000Z' }, { sourceSequence: '2' }]; for (const variation of variations) assert.equal(value(classify(fact('obs/2', variation), [original])).classification, 'conflict'); });

test('existing correction graph is fully validated even for unrelated incoming facts', () => { const root = fact('obs/root'), correction = fact('obs/c1', { payloadHash: hash('b'), correctsObservationRef: 'obs/root' }); error(classify(fact('obs/new', { payloadHash: hash('f') }), [correction]), 'missing_parent'); const fork = fact('obs/c2', { payloadHash: hash('c'), correctsObservationRef: 'obs/root' }); error(classify(fact('obs/new', { payloadHash: hash('f') }), [root, correction, fork]), 'correction_fork'); const cross = fact('obs/cross', { payloadHash: hash('b'), correctsObservationRef: 'obs/root', scope: scope({ eventId: 'event:other' }) }); error(classify(fact('obs/new', { payloadHash: hash('f') }), [root, cross]), 'correction_scope_conflict'); const unchanged = fact('obs/unchanged', { correctsObservationRef: 'obs/root' }); error(classify(fact('obs/new', { payloadHash: hash('f') }), [root, unchanged]), 'contradictory_supersession'); const a = fact('obs/a', { payloadHash: hash('b'), correctsObservationRef: 'obs/b' }), b = fact('obs/b', { payloadHash: hash('c'), correctsObservationRef: 'obs/a' }); error(classify(fact('obs/new', { payloadHash: hash('f') }), [a, b]), 'correction_cycle'); error(classify(fact('obs/new', { payloadHash: hash('f') }), [root, { ...root }]), 'repeated_reference'); });

test('valid corrections remain append-only and incoming forks are already superseded', () => { const root = fact('obs/root', { sourceSequence: '1' }), correction = fact('obs/c1', { payloadHash: hash('b'), correctsObservationRef: 'obs/root', sourceSequence: '2', observedAt: '2026-08-28T00:59:00.000Z' }); const result = value(classify(correction, [root])); assert.equal(result.classification, 'correction'); assert.equal(result.ordering.sequenceTimestampDisagreement, true); assert.equal(root.payloadHash, hash('a')); const other = fact('obs/c2', { payloadHash: hash('c'), correctsObservationRef: 'obs/root' }); assert.equal(value(classify(other, [root, correction])).classification, 'already_superseded'); });

test('exported ordering boundary validates hostile, malformed and permuted runtime input', () => { const first = fact('obs/a', { sourceSequence: '1' }), second = fact('obs/b', { sourceSequence: '2' }); const decision = value(compareObservationOrder({ first, second })); assert.equal(decision.order, 'first_before_second'); assert.equal(value(compareObservationOrder({ first: second, second: first })).order, 'second_before_first'); for (const input of [null, undefined, 1, 'x', {}, { first: null, second }]) error(compareObservationOrder(input), 'invalid_input'); const hostile = new Proxy({}, { ownKeys() { throw new Error('hidden'); } }); error(compareObservationOrder(hostile), 'invalid_input'); error(compareObservationOrder({ first: fact('obs/a', { observationRef: 'x'.repeat(257) }), second }), 'invalid_reference'); });

test('fact and correction-chain limits fail closed with frozen results', () => { const tooMany = Array.from({ length: MAX_OBSERVATION_FACTS + 1 }, (_, index) => fact(`obs/${index}`, { payloadHash: `sha256:${index.toString(16).padStart(64, '0')}` })); error(classify(fact('obs/new', { payloadHash: hash('f') }), tooMany), 'limit_exceeded'); const exactChain = Array.from({ length: MAX_OBSERVATION_FACTS }, (_, index) => fact(`chain/${index}`, { payloadHash: `sha256:${index.toString(16).padStart(64, '0')}`, ...(index ? { correctsObservationRef: `chain/${index - 1}` } : {}) })); assert.equal(classify(fact('obs/unrelated', { payloadHash: hash('f') }), exactChain).ok, true); error(classify(fact('chain/overflow', { payloadHash: `sha256:${MAX_OBSERVATION_FACTS.toString(16).padStart(64, '0')}`, correctsObservationRef: `chain/${MAX_OBSERVATION_FACTS - 1}` }), exactChain), 'correction_chain_limit_exceeded'); const result = classify(fact('obs/new')); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.value.scope)); });

test('payload verification encodes once, handles multibyte boundaries, and hashes byte subviews', async () => { const Original = globalThis.TextEncoder; let calls = 0; globalThis.TextEncoder = class extends Original { encode(value) { calls += 1; return super.encode(value); } }; try { const text = 'é'; const expected = `sha256:${createHash('sha256').update(text).digest('hex')}`; assert.equal(value(await verifyPayloadHash({ payloadHash: expected, replayMode: 'hash_only_verification' }, text)).status, 'verified'); assert.equal(calls, 1); } finally { globalThis.TextEncoder = Original; }
  const exact = 'é'.repeat(PAYLOAD_HASH_POLICY.maxPayloadBytes / 2), exactHash = `sha256:${createHash('sha256').update(exact).digest('hex')}`; assert.equal(value(await verifyPayloadHash({ payloadHash: exactHash, replayMode: 'full_payload_retained' }, exact)).payloadByteLength, PAYLOAD_HASH_POLICY.maxPayloadBytes); error(await verifyPayloadHash({ payloadHash: exactHash, replayMode: 'full_payload_retained' }, `${exact}é`), 'payload_too_large'); const backing = new Uint8Array([9, 1, 2, 3, 9]), subview = backing.subarray(1, 4), subHash = `sha256:${createHash('sha256').update(subview).digest('hex')}`; assert.equal(value(await verifyPayloadHash({ payloadHash: subHash, replayMode: 'full_payload_retained' }, subview)).status, 'verified'); });

test('payload empty, one-over, mismatch, not-verifiable and hostile behaviour is preserved', async () => { const emptyHash = 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'; assert.equal(value(await verifyPayloadHash({ payloadHash: emptyHash, replayMode: 'full_payload_retained' }, new Uint8Array())).status, 'verified'); assert.equal(value(await verifyPayloadHash({ payloadHash: hash('0'), replayMode: 'full_payload_retained' }, new Uint8Array())).status, 'mismatch'); error(await verifyPayloadHash({ payloadHash: hash('0'), replayMode: 'full_payload_retained' }, new Uint8Array(PAYLOAD_HASH_POLICY.maxPayloadBytes + 1)), 'payload_too_large'); for (const replayMode of ['full_payload_retained', 'hash_and_retrievable_locator', 'hash_only_verification', 'not_fully_replayable']) assert.equal(value(await verifyPayloadHash({ payloadHash: hash('0'), replayMode })).status, 'not_verifiable'); const hostile = new Proxy(new Uint8Array([1]), { getPrototypeOf() { throw new Error('hidden'); } }); error(await verifyPayloadHash({ payloadHash: hash('0'), replayMode: 'full_payload_retained' }, hostile), 'invalid_payload'); });

test('ASCII, unpaired-surrogate and detached-buffer boundaries remain bounded', async () => { const ascii = 'a'.repeat(PAYLOAD_HASH_POLICY.maxPayloadBytes), asciiHash = `sha256:${createHash('sha256').update(ascii).digest('hex')}`; assert.equal(value(await verifyPayloadHash({ payloadHash: asciiHash, replayMode: 'full_payload_retained' }, ascii)).payloadByteLength, PAYLOAD_HASH_POLICY.maxPayloadBytes); error(await verifyPayloadHash({ payloadHash: asciiHash, replayMode: 'full_payload_retained' }, `${ascii}a`), 'payload_too_large'); const lone = '\ud800'.repeat(Math.floor(PAYLOAD_HASH_POLICY.maxPayloadBytes / 3)), remainder = 'a'.repeat(PAYLOAD_HASH_POLICY.maxPayloadBytes % 3), surrogateBoundary = `${lone}${remainder}`, surrogateHash = `sha256:${createHash('sha256').update(surrogateBoundary).digest('hex')}`; assert.equal(value(await verifyPayloadHash({ payloadHash: surrogateHash, replayMode: 'full_payload_retained' }, surrogateBoundary)).payloadByteLength, PAYLOAD_HASH_POLICY.maxPayloadBytes); error(await verifyPayloadHash({ payloadHash: surrogateHash, replayMode: 'full_payload_retained' }, `${surrogateBoundary}a`), 'payload_too_large'); const bytes = new Uint8Array([1, 2, 3]); structuredClone(bytes.buffer, { transfer: [bytes.buffer] }); error(await verifyPayloadHash({ payloadHash: hash('0'), replayMode: 'full_payload_retained' }, bytes), 'invalid_payload'); });

test('replay stays deterministic without clock, randomness or network', () => { const input = { aliasSet: set(alias('resolved')), candidates: [candidate()], asOf: at, policy: ALIAS_RESOLUTION_POLICY }; assert.deepEqual(resolveProviderAlias(input), resolveProviderAlias(input)); const now = Date.now, random = Math.random; Date.now = () => { throw new Error('clock'); }; Math.random = () => { throw new Error('random'); }; try { assert.equal(resolveProviderAlias(input).ok, true); assert.equal(classify(fact('obs/new')).ok, true); } finally { Date.now = now; Math.random = random; } });

test('result mapping decisions can only be issued from live exact participant resolutions', () => {
  const stored = contextualAlias('participant', { externalKey: 'provider-participant:a', canonicalId: 'participant:opaque-a', sportId: 'sport:opaque-1', competitionId: 'competition:opaque-1' }), exact = contextualCandidate('participant', { externalKey: 'provider-participant:a', canonicalId: 'participant:opaque-a', sportId: 'sport:opaque-1', competitionId: 'competition:opaque-1' }); const resolution = value(resolve(set(stored), [exact])); const eventStored = alias('resolved', { externalKey: 'provider-event:1' }), eventExact = candidate('event:opaque-1', 'candidate:event', { externalKey: 'provider-event:1' }), eventResolution = value(resolve(set(eventStored), [eventExact])), eventIdentity = value(normalizeCanonicalIdentity(identity())); const context = { decisionRef: 'mapping-decision:a', providerRoleRef: 'provider-role:home', roleId: 'role:home-1', role: 'home' }; const issued = value(issueResultMappingDecision(context, resolution, eventResolution, eventIdentity)); assert.equal(issued.aliasRef, stored.aliasRef); assert.equal(issued.participantId, 'participant:opaque-a'); assert.ok(Object.isFrozen(issued)); assert.ok(Object.isFrozen(issued.supportingEvidenceRefs));
  error(issueResultMappingDecision(context, { ...resolution }, eventResolution, eventIdentity), 'untrusted_alias_resolution'); error(issueResultMappingDecision(context, JSON.parse(JSON.stringify(resolution)), eventResolution, eventIdentity), 'untrusted_alias_resolution'); error(issueResultMappingDecision(context, resolution, eventResolution, { ...eventIdentity }), 'untrusted_canonical_identity');
  const unresolvedStored = contextualAlias('participant', { status: 'unresolved', externalKey: 'provider-participant:a', competitionId: 'competition:opaque-1' }); delete unresolvedStored.canonicalId; const unresolved = value(resolve(set(unresolvedStored), [])); error(issueResultMappingDecision(context, unresolved, eventResolution, eventIdentity), 'unresolved_mapping_evidence');
  const similarityStored = contextualAlias('participant', { status: 'unresolved', externalKey: 'provider-participant:a', competitionId: 'competition:opaque-1' }); delete similarityStored.canonicalId; const similarityOnly = value(resolve(set(similarityStored), [contextualCandidate('participant', { externalKey: 'provider-participant:a', competitionId: 'competition:opaque-1', evidenceKind: 'display_name_similarity' })])); error(issueResultMappingDecision(context, similarityOnly, eventResolution, eventIdentity), 'unresolved_mapping_evidence');
});
