import { canonicalizeJson } from './canonical-json.ts';
import { deepFreeze, fail, ok, snapshot, timestamp, type DomainResult } from './domain-validation.ts';
import { normalizeMarketObservation, type NormalizedMarketSnapshot } from './market-observation.ts';
import { calculateDeleteAfter, RETENTION_CONTRACT_VERSION, validateRightsSchedule, type IntelligenceRecordType, type IntelligenceSourceClass, type RightsSchedule } from './intelligence-rights.ts';
import type { JsonValue } from './untrusted-json.ts';

export const INTELLIGENCE_RECORD_SCHEMA_VERSION='mk-intelligence-record-jcs/1',INTELLIGENCE_RECORD_CONTRACT_VERSION='authenticated-intelligence-record/1',HMAC_ALGORITHM='HMAC-SHA-256';
export const HMAC_DOMAIN_SEPARATOR='MKALMA\0INTELLIGENCE_RECORD\0HMAC_SHA256\0v1\0';
export const RECORD_LIMITS=Object.freeze({maxPayloadBytes:49_152,maxParentRefs:16,maxRecordIdLength:128,maxVersionIdLength:64,maxReferenceLength:256,maxAuditMetadataBytes:2_048,maxQuarantineMetadataBytes:2_048} as const);
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]*$/,HEX=/^[0-9a-f]+$/,encoder=new TextEncoder(),manualDecisions=new WeakSet<object>();
export type KeyStatus='active'|'verify-only'|'revoked'|'unavailable';
export interface VerificationKey{readonly environmentId:string;readonly keyId:string;readonly algorithm:typeof HMAC_ALGORITHM;readonly status:KeyStatus;readonly activatesAt:string;readonly verifyUntil?:string;readonly cryptoKey:CryptoKey}
export interface SigningKey extends VerificationKey{readonly status:'active'}
export interface IntelligenceVerificationKeyProvider{getVerificationKey(environmentId:string,keyId:string,at:string):Promise<VerificationKey|undefined>}
export interface IntelligenceSigningKeyProvider{getActiveSigningKey(environmentId:string,at:string):Promise<SigningKey|undefined>}

export interface TrustedManualProvenanceDecision{readonly version:'trusted-manual-provenance-decision/1';readonly environmentId:string;readonly scheduleId:string;readonly sourceId:string;readonly providerRef:string;readonly ownershipEvidenceRef:string;readonly importAuthorized:boolean;readonly authorizedAt:string}
export interface ManualProvenanceAuthority{authorize(input:Readonly<{environmentId:string;schedule:RightsSchedule;payload:NormalizedMarketSnapshot}>):Promise<TrustedManualProvenanceDecision|undefined>}
export function createManualProvenanceAuthority(authorize:(input:Readonly<{environmentId:string;schedule:RightsSchedule;payload:NormalizedMarketSnapshot}>)=>Promise<Omit<TrustedManualProvenanceDecision,'version'>|undefined>):ManualProvenanceAuthority{return Object.freeze({async authorize(input:Readonly<{environmentId:string;schedule:RightsSchedule;payload:NormalizedMarketSnapshot}>){const raw=await authorize(input);if(!raw)return undefined;const decision=deepFreeze({version:'trusted-manual-provenance-decision/1' as const,...raw});manualDecisions.add(decision);return decision;}})}

export interface IntelligenceRecordHeader{readonly recordType:IntelligenceRecordType;readonly recordId:string;readonly schemaVersion:typeof INTELLIGENCE_RECORD_SCHEMA_VERSION;readonly contractVersion:typeof INTELLIGENCE_RECORD_CONTRACT_VERSION;readonly environmentId:string;readonly streamId:string;readonly parentRefs:readonly string[];readonly correctsRecordId?:string;readonly issuedAt:string;readonly validatedAt:string;readonly issuer:string;readonly keyId:string;readonly rightsScheduleId:string;readonly retentionPolicyVersion:typeof RETENTION_CONTRACT_VERSION;readonly sourceClass:IntelligenceSourceClass;readonly provenanceContractVersion:RightsSchedule['provenanceContractVersion'];readonly ownershipEvidenceRef?:string;readonly rawPayloadPolicy:RightsSchedule['rawPayloadPolicy'];readonly providerDisposition:'not_provider_derived';readonly projectDeleteAfter?:string;readonly hardSourceDeleteAfter?:string;readonly indefiniteBasis?:'project_owned_synthetic_fixture';readonly legalHold:false;readonly replayMode:'full_payload_retained'}
export interface AuthenticatedIntelligenceRecord extends IntelligenceRecordHeader{readonly payload:JsonValue;readonly contentHash:string;readonly authenticationTag:string}
export interface IssueRecordInput extends Omit<IntelligenceRecordHeader,'schemaVersion'|'contractVersion'|'keyId'|'rightsScheduleId'|'retentionPolicyVersion'|'sourceClass'|'provenanceContractVersion'|'ownershipEvidenceRef'|'rawPayloadPolicy'|'providerDisposition'|'projectDeleteAfter'|'hardSourceDeleteAfter'|'indefiniteBasis'|'legalHold'|'replayMode'>{readonly payload:unknown;readonly rightsSchedule:unknown}
export interface IssuanceDependencies{readonly keys:IntelligenceSigningKeyProvider;readonly manualAuthority?:ManualProvenanceAuthority}

function safeFailure<T>(code:string,message:string,path:string):DomainResult<T>{return fail(code,message,path)}
function exactBuffer(bytes:Uint8Array):ArrayBuffer{const copy=new Uint8Array(bytes.byteLength);copy.set(bytes);return copy.buffer}
function hex(bytes:ArrayBuffer):string{return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function frame(header:Uint8Array,payload:Uint8Array):Uint8Array{const d=encoder.encode(HMAC_DOMAIN_SEPARATOR),out=new Uint8Array(d.length+8+header.length+payload.length),v=new DataView(out.buffer);out.set(d);v.setUint32(d.length,header.length,false);out.set(header,d.length+4);v.setUint32(d.length+4+header.length,payload.length,false);out.set(payload,d.length+8+header.length);return out}
export function constantTimeEqual(left:Uint8Array,right:Uint8Array):boolean{let different=left.length^right.length;const length=Math.max(left.length,right.length);for(let i=0;i<length;i+=1)different|=(left[i%(left.length||1)]??0)^(right[i%(right.length||1)]??0);return different===0}
function cryptoPolicy(key:VerificationKey,usage:'sign'|'verify',environmentId:string,keyId?:string):boolean{const algorithm=key.cryptoKey?.algorithm as KeyAlgorithm&{hash?:KeyAlgorithm},usages=key.cryptoKey?.usages??[];return key.algorithm===HMAC_ALGORITHM&&key.environmentId===environmentId&&(!keyId||key.keyId===keyId)&&key.cryptoKey?.type==='secret'&&algorithm?.name==='HMAC'&&algorithm.hash?.name==='SHA-256'&&usages.includes(usage)&&(key.status!=='verify-only'||(usage==='verify'&&!usages.includes('sign')))}
function headerOf(record:AuthenticatedIntelligenceRecord|Record<string,unknown>):IntelligenceRecordHeader{const v=record as unknown as IntelligenceRecordHeader;return{recordType:v.recordType,recordId:v.recordId,schemaVersion:v.schemaVersion,contractVersion:v.contractVersion,environmentId:v.environmentId,streamId:v.streamId,parentRefs:v.parentRefs,...(v.correctsRecordId?{correctsRecordId:v.correctsRecordId}:{}),issuedAt:v.issuedAt,validatedAt:v.validatedAt,issuer:v.issuer,keyId:v.keyId,rightsScheduleId:v.rightsScheduleId,retentionPolicyVersion:v.retentionPolicyVersion,sourceClass:v.sourceClass,provenanceContractVersion:v.provenanceContractVersion,...(v.ownershipEvidenceRef?{ownershipEvidenceRef:v.ownershipEvidenceRef}:{}),rawPayloadPolicy:v.rawPayloadPolicy,providerDisposition:v.providerDisposition,...(v.projectDeleteAfter?{projectDeleteAfter:v.projectDeleteAfter}:{}),...(v.hardSourceDeleteAfter?{hardSourceDeleteAfter:v.hardSourceDeleteAfter}:{}),...(v.indefiniteBasis?{indefiniteBasis:v.indefiniteBasis}:{}),legalHold:v.legalHold,replayMode:v.replayMode}}
function parseId(value:unknown,path:string,max=128):DomainResult<string>{return typeof value==='string'&&value.length>0&&value.length<=max&&ID.test(value)?ok(value):fail('invalid_input','Invalid bounded identifier.',path)}

export function validateRecordHeader(input:unknown):DomainResult<IntelligenceRecordHeader>{
 const safe=snapshot(input);if(!safe.ok)return safeFailure('invalid_input','Header failed bounded inspection.',safe.error.path);if(typeof safe.value!=='object'||safe.value===null||Array.isArray(safe.value))return fail('malformed_envelope','Header must be an object.','$');const v=safe.value as Record<string,unknown>;
 const allowed=new Set(['recordType','recordId','schemaVersion','contractVersion','environmentId','streamId','parentRefs','correctsRecordId','issuedAt','validatedAt','issuer','keyId','rightsScheduleId','retentionPolicyVersion','sourceClass','provenanceContractVersion','ownershipEvidenceRef','rawPayloadPolicy','providerDisposition','projectDeleteAfter','hardSourceDeleteAfter','indefiniteBasis','legalHold','replayMode']);for(const key of Object.keys(v))if(!allowed.has(key))return fail('unknown_field','Unknown authenticated header field.',`$.${key}`);
 if(v.recordType!=='market_observation'&&v.recordType!=='canonical_result_observation')return fail('unsupported_record_type','Record type is unsupported.','$.recordType');for(const[field,max]of[['recordId',128],['environmentId',128],['streamId',128],['issuer',128],['keyId',64],['rightsScheduleId',128]]as const){const p=parseId(v[field],`$.${field}`,max);if(!p.ok)return p}
 if(v.schemaVersion!==INTELLIGENCE_RECORD_SCHEMA_VERSION||v.contractVersion!==INTELLIGENCE_RECORD_CONTRACT_VERSION||v.retentionPolicyVersion!==RETENTION_CONTRACT_VERSION)return fail('unsupported_version','Envelope version is unsupported.','$');if(!Array.isArray(v.parentRefs)||v.parentRefs.length>RECORD_LIMITS.maxParentRefs)return fail('parent_limit_exceeded','Parent limit exceeded.','$.parentRefs');const parents:string[]=[];for(let i=0;i<v.parentRefs.length;i+=1){const p=parseId(v.parentRefs[i],`$.parentRefs[${i}]`);if(!p.ok)return p;if(i&&parents[i-1]>=p.value)return fail('invalid_parent_order','Parents must be unique and ordered.',`$.parentRefs[${i}]`);parents.push(p.value)}
 const issued=timestamp(v.issuedAt as never,'$.issuedAt'),validated=timestamp(v.validatedAt as never,'$.validatedAt');if(!issued.ok)return issued;if(!validated.ok)return validated;if(validated.value.milliseconds<issued.value.milliseconds)return fail('invalid_time_order','validatedAt precedes issuedAt.','$.validatedAt');
 const manual=v.sourceClass==='manual_user_owned';if(!manual&&v.sourceClass!=='synthetic_project_owned')return fail('payload_rights_mismatch','Unsupported source class.','$.sourceClass');if(v.provenanceContractVersion!==(manual?'user-owned-manual-provenance/1':'project-synthetic-provenance/1')||v.rawPayloadPolicy!==(manual?'user_authored_fixture_allowed':'project_fixture_allowed')||v.providerDisposition!=='not_provider_derived'||v.legalHold!==false||v.replayMode!=='full_payload_retained')return fail('payload_rights_mismatch','Header rights fields contradict source class.','$');if(manual!== (typeof v.ownershipEvidenceRef==='string'))return fail('payload_rights_mismatch','Ownership evidence binding is inconsistent.','$.ownershipEvidenceRef');
 if((v.projectDeleteAfter===undefined)===(v.indefiniteBasis===undefined))return fail('invalid_retention','Exactly one project deadline or indefinite basis is required.','$');for(const field of ['projectDeleteAfter','hardSourceDeleteAfter']as const)if(v[field]!==undefined){const t=timestamp(v[field] as never,`$.${field}`);if(!t.ok)return t;if(t.value.milliseconds<=issued.value.milliseconds)return fail('invalid_retention','Deletion deadline must follow issuance.',`$.${field}`)}if(v.indefiniteBasis!==undefined&&v.indefiniteBasis!=='project_owned_synthetic_fixture')return fail('invalid_retention','Unsupported indefinite basis.','$.indefiniteBasis');if(manual&&!v.hardSourceDeleteAfter)return fail('invalid_retention','Manual source deadline is required.','$.hardSourceDeleteAfter');
 if(v.correctsRecordId!==undefined){const c=parseId(v.correctsRecordId,'$.correctsRecordId');if(!c.ok)return c;if(!parents.includes(c.value))return fail('correction_parent_required','Correction target must be a parent.','$.correctsRecordId')}return ok(deepFreeze({...v,parentRefs:parents}as unknown as IntelligenceRecordHeader));
}

async function validatePayloadRights(recordType:unknown,payload:unknown,schedule:RightsSchedule,environmentId:string,authority?:ManualProvenanceAuthority):Promise<DomainResult<{payload:NormalizedMarketSnapshot;ownershipEvidenceRef?:string}>>{
 if(recordType!=='market_observation')return fail('unsupported_record_type','No honest issuance adapter exists for this record type.','$.recordType');const normalized=normalizeMarketObservation(payload);if(!normalized.ok)return fail('domain_invalid','Payload failed current market validation.',normalized.error.path);const source=normalized.value.sourceEnvelope;
 if(source.retention.replayMode!=='full_payload_retained'||source.termsRef!==`rights:${schedule.scheduleId}`)return fail('payload_rights_mismatch','Replay or rights reference does not match schedule.','$.payload.sourceEnvelope');
 if(schedule.sourceClass==='synthetic_project_owned'){if(!(source.sourceId.startsWith('synthetic-')||source.sourceId.startsWith('project:'))||!source.providerRef.startsWith('project:')||source.retrievalMethod!=='manual'||/(bookmaker|provider-feed|licensed)/i.test(`${source.sourceId} ${source.providerRef}`))return fail('payload_rights_mismatch','Synthetic provenance is not internally project-owned.','$.payload.sourceEnvelope');return ok({payload:normalized.value})}
 if(source.retrievalMethod==='licensed_api'||!source.sourceId.startsWith('manual-user-')||!source.providerRef.startsWith('user-owned:')||/(bookmaker|provider-feed|third-party|licensed)/i.test(`${source.sourceId} ${source.providerRef}`)||!authority)return fail('payload_rights_mismatch','Manual provenance is not explicitly user-owned.','$.payload.sourceEnvelope');
 let decision:TrustedManualProvenanceDecision|undefined;try{decision=await authority.authorize({environmentId,schedule,payload:normalized.value})}catch{return fail('provider_or_port_failure','Manual provenance authority failed.','$.payload.sourceEnvelope')}
 if(!decision||!manualDecisions.has(decision)||decision.environmentId!==environmentId||decision.scheduleId!==schedule.scheduleId||decision.sourceId!==source.sourceId||decision.providerRef!==source.providerRef||decision.ownershipEvidenceRef!==schedule.authorizationEvidenceRef||(source.retrievalMethod==='file_import'&&!decision.importAuthorized))return fail('payload_rights_mismatch','Manual ownership authority does not bind this payload.','$.payload.sourceEnvelope');return ok({payload:normalized.value,ownershipEvidenceRef:decision.ownershipEvidenceRef});
}

export async function issueAuthenticatedRecord(input:unknown,dependencies:IntelligenceSigningKeyProvider|IssuanceDependencies):Promise<DomainResult<AuthenticatedIntelligenceRecord>>{
 const safe=snapshot(input);if(!safe.ok)return fail('invalid_input','Issuance input failed bounded inspection.',safe.error.path);if(typeof safe.value!=='object'||safe.value===null||Array.isArray(safe.value))return fail('invalid_input','Issuance input must be an object.','$');const v=safe.value as unknown as IssueRecordInput;let deps:IssuanceDependencies;try{deps=typeof dependencies==='object'&&dependencies!==null&&'keys'in dependencies?dependencies:{keys:dependencies as IntelligenceSigningKeyProvider}}catch{return fail('key_provider_failure','Signing dependency boundary failed.','$.keyId')}
 const rights=validateRightsSchedule(v.rightsSchedule);if(!rights.ok)return rights;if(!rights.value.permittedRecordTypes.includes(v.recordType))return fail('payload_rights_mismatch','Rights schedule does not permit the record type.','$.recordType');const validated=await validatePayloadRights(v.recordType,v.payload,rights.value,v.environmentId,deps.manualAuthority);if(!validated.ok)return validated;
 let key:SigningKey|undefined;try{key=await deps.keys.getActiveSigningKey(v.environmentId,v.issuedAt)}catch{return fail('key_provider_failure','Signing key provider failed.','$.keyId')}if(!key)return fail('signing_key_unavailable','No active signing key is available.','$.keyId');if(key.status!=='active'||!cryptoPolicy(key,'sign',v.environmentId))return fail('key_policy_mismatch','Signing key violates key policy.','$.keyId');
 const projectDeleteAfter=calculateDeleteAfter(rights.value,v.issuedAt),header={recordType:v.recordType,recordId:v.recordId,schemaVersion:INTELLIGENCE_RECORD_SCHEMA_VERSION,contractVersion:INTELLIGENCE_RECORD_CONTRACT_VERSION,environmentId:v.environmentId,streamId:v.streamId,parentRefs:v.parentRefs,...(v.correctsRecordId?{correctsRecordId:v.correctsRecordId}:{}),issuedAt:v.issuedAt,validatedAt:v.validatedAt,issuer:v.issuer,keyId:key.keyId,rightsScheduleId:rights.value.scheduleId,retentionPolicyVersion:RETENTION_CONTRACT_VERSION,sourceClass:rights.value.sourceClass,provenanceContractVersion:rights.value.provenanceContractVersion,...(validated.value.ownershipEvidenceRef?{ownershipEvidenceRef:validated.value.ownershipEvidenceRef}:{}),rawPayloadPolicy:rights.value.rawPayloadPolicy,providerDisposition:'not_provider_derived' as const,...(projectDeleteAfter?{projectDeleteAfter}:{indefiniteBasis:rights.value.indefiniteBasis}),...(rights.value.hardSourceRightsDeleteAfter?{hardSourceDeleteAfter:rights.value.hardSourceRightsDeleteAfter}:{}),legalHold:false as const,replayMode:'full_payload_retained' as const};const parsed=validateRecordHeader(header);if(!parsed.ok)return parsed;
 try{const canonicalDomainValue=JSON.parse(JSON.stringify(validated.value.payload))as JsonValue,payloadBytes=canonicalizeJson(canonicalDomainValue,RECORD_LIMITS.maxPayloadBytes),contentHash=`sha256:${hex(await crypto.subtle.digest('SHA-256',exactBuffer(payloadBytes)))}`,mac=await crypto.subtle.sign('HMAC',key.cryptoKey,exactBuffer(frame(canonicalizeJson(parsed.value),payloadBytes)));return ok(deepFreeze({...parsed.value,payload:JSON.parse(new TextDecoder().decode(payloadBytes))as JsonValue,contentHash,authenticationTag:`hmac-sha256:${hex(mac)}`}))}catch{return fail('cryptographic_failure','Record authentication failed.','$')}
}

export async function verifyAuthenticatedRecord(input:unknown,expectedEnvironment:string,keys:IntelligenceVerificationKeyProvider):Promise<DomainResult<AuthenticatedIntelligenceRecord>>{
 const safe=snapshot(input);if(!safe.ok)return fail('invalid_input','Envelope failed bounded inspection.',safe.error.path);if(typeof safe.value!=='object'||safe.value===null||Array.isArray(safe.value))return fail('malformed_envelope','Envelope must be an object.','$');const v=safe.value as Record<string,unknown>,allowed=new Set([...Object.keys(headerOf(v)),'payload','contentHash','authenticationTag']);for(const key of Object.keys(v))if(!allowed.has(key))return fail('unknown_field','Unknown envelope field.',`$.${key}`);if(!Object.hasOwn(v,'payload')||typeof v.contentHash!=='string'||typeof v.authenticationTag!=='string')return fail('malformed_envelope','Payload, hash and tag are required.','$');const header=validateRecordHeader(headerOf(v));if(!header.ok)return header;if(header.value.environmentId!==expectedEnvironment)return fail('wrong_environment','Record belongs to another environment.','$.environmentId');
 let payloadBytes:Uint8Array,actualHash:string;try{payloadBytes=canonicalizeJson(v.payload,RECORD_LIMITS.maxPayloadBytes);actualHash=`sha256:${hex(await crypto.subtle.digest('SHA-256',exactBuffer(payloadBytes)))}`}catch{return fail('cryptographic_failure','Payload hashing failed.','$.payload')}if(!constantTimeEqual(encoder.encode(actualHash),encoder.encode(v.contentHash)))return fail('hash_mismatch','Content hash failed.','$.contentHash');
 let key:VerificationKey|undefined;try{key=await keys.getVerificationKey(expectedEnvironment,header.value.keyId,header.value.issuedAt)}catch{return fail('key_provider_failure','Verification key provider failed.','$.keyId')}if(!key)return fail('unknown_key','Verification key is unavailable.','$.keyId');if(key.status==='revoked'||key.status==='unavailable')return fail('revoked_key','Verification key is not permitted.','$.keyId');if(!cryptoPolicy(key,'verify',expectedEnvironment,header.value.keyId))return fail('key_policy_mismatch','Verification key violates key policy.','$.keyId');if(Date.parse(header.value.issuedAt)<Date.parse(key.activatesAt)||(key.verifyUntil&&Date.parse(header.value.issuedAt)>=Date.parse(key.verifyUntil)))return fail('key_period_invalid','Record is outside key period.','$.issuedAt');if(!v.authenticationTag.startsWith('hmac-sha256:')||v.authenticationTag.length!==76||!HEX.test(v.authenticationTag.slice(12)))return fail('malformed_envelope','Tag encoding is invalid.','$.authenticationTag');
 try{const supplied=Uint8Array.from(v.authenticationTag.slice(12).match(/../g)??[],p=>Number.parseInt(p,16)),valid=await crypto.subtle.verify('HMAC',key.cryptoKey,exactBuffer(supplied),exactBuffer(frame(canonicalizeJson(header.value),payloadBytes)));if(!valid)return fail('mac_mismatch','Authentication failed.','$.authenticationTag')}catch{return fail('cryptographic_failure','Authentication operation failed.','$.authenticationTag')}return ok(deepFreeze({...header.value,payload:JSON.parse(new TextDecoder().decode(payloadBytes))as JsonValue,contentHash:actualHash,authenticationTag:v.authenticationTag}));
}
export type{RightsSchedule};
