import type { JsonValue } from './untrusted-json.ts';
import { DOMAIN_REASON_MAX, DOMAIN_VERSION_MAX, boundedText, fail, identifier, isRecord, ok, record, reference, shape, snapshot, stringArray, timestamp, type DomainError, type DomainResult } from './domain-validation.ts';

export const CANONICAL_IDENTITY_CONTRACT_VERSION = 'canonical-identity-v2';
export const ALIAS_CONTRACT_VERSION = 'provider-alias-v2';
export const ALIAS_SET_CONTRACT_VERSION = 'provider-alias-set-v1';
export const ALIAS_RESOLUTION_POLICY = Object.freeze({ id: 'exact-evidence-only-alias-set', version: '2' } as const);
export const MAX_EVENT_PARTICIPANTS = 16, MAX_ALIAS_CANDIDATES = 16, MAX_ALIASES = 16, MAX_ALIAS_CHAIN_DEPTH = 16, MAX_EVIDENCE_REFS = 16;
export type CanonicalEntityType = 'sport' | 'competition' | 'participant' | 'event';
export type TaggedCanonicalId = `${CanonicalEntityType}:${string}`;
export type AliasStatus = 'resolved' | 'unresolved' | 'ambiguous' | 'quarantined' | 'superseded';

export interface CanonicalEventParticipant { readonly participantId: `participant:${string}`; readonly roleId: `role:${string}`; readonly role: 'home' | 'away' | 'competitor' | 'draw'; readonly roleVersion: string; readonly evidenceRefs: readonly string[] }
export interface CanonicalIdentity { readonly contractVersion: typeof CANONICAL_IDENTITY_CONTRACT_VERSION; readonly entityType: CanonicalEntityType; readonly canonicalId: TaggedCanonicalId; readonly version: string; readonly evidenceRefs: readonly string[]; readonly sportId?: `sport:${string}`; readonly competitionId?: `competition:${string}`; readonly eventStartAt?: string; readonly participants?: readonly CanonicalEventParticipant[] }
export interface ProviderAlias { readonly contractVersion: typeof ALIAS_CONTRACT_VERSION; readonly aliasRef: string; readonly entityType: CanonicalEntityType; readonly sourceId: string; readonly providerRef: string; readonly externalKey: string; readonly canonicalId?: TaggedCanonicalId; readonly historicalCanonicalId?: TaggedCanonicalId; readonly sportId?: `sport:${string}`; readonly competitionId?: `competition:${string}`; readonly eventStartAt?: string; readonly effectiveFrom: string; readonly effectiveTo?: string; readonly status: AliasStatus; readonly evidenceRefs: readonly string[]; readonly version: string; readonly viableCandidateRefs?: readonly string[]; readonly quarantineReason?: string; readonly supersededByAliasRef?: string; readonly supersessionReason?: string }
export interface AliasCandidate { readonly candidateRef: string; readonly canonicalId: TaggedCanonicalId; readonly entityType: CanonicalEntityType; readonly sourceId: string; readonly providerRef: string; readonly externalKey: string; readonly sportId?: `sport:${string}`; readonly competitionId?: `competition:${string}`; readonly eventStartAt?: string; readonly evidenceRefs: readonly string[]; readonly evidenceKind: 'exact_source_key' | 'display_name_similarity' }
export interface AliasSet { readonly contractVersion: typeof ALIAS_SET_CONTRACT_VERSION; readonly aliases: readonly ProviderAlias[] }
export interface AliasResolution { readonly contractVersion: 'alias-resolution-v2'; readonly status: AliasStatus; readonly alias: ProviderAlias; readonly aliasSet: AliasSet; readonly policy: typeof ALIAS_RESOLUTION_POLICY; readonly evaluatedAt: string; readonly reason: string; readonly canonicalId?: TaggedCanonicalId; readonly historicalCanonicalId?: TaggedCanonicalId; readonly candidateRefs: readonly string[]; readonly evidenceRefs: readonly string[] }
export interface ResolverIssuedResultMappingDecision { readonly contractVersion: 'resolver-issued-result-mapping-v1'; readonly decisionRef: string; readonly resolverContractVersion: 'alias-resolution-v2'; readonly resolverPolicy: typeof ALIAS_RESOLUTION_POLICY; readonly aliasContractVersion: typeof ALIAS_CONTRACT_VERSION; readonly aliasRef: string; readonly aliasVersion: string; readonly aliasStatus: 'resolved'; readonly effectiveFrom: string; readonly effectiveTo?: string; readonly evaluatedAt: string; readonly supportingEvidenceRefs: readonly string[]; readonly sourceId: string; readonly providerRef: string; readonly providerEventRef: string; readonly providerParticipantRef: string; readonly providerRoleRef: string; readonly sportId: `sport:${string}`; readonly competitionId: `competition:${string}`; readonly eventId: `event:${string}`; readonly participantId: `participant:${string}`; readonly roleId: `role:${string}`; readonly role: CanonicalEventParticipant['role']; readonly identityContractVersion: string; readonly resolutionStatus: 'resolved'; readonly resolutionKind: 'exact_source_key' }

const issuedAliasResolutions = new WeakSet<object>();
const issuedResultMappingDecisions = new WeakSet<object>();
const issuedCanonicalIdentities = new WeakSet<object>();

function enumValue<T extends string>(value: JsonValue | undefined, values: readonly T[], path: string): DomainResult<T> { return typeof value === 'string' && values.includes(value as T) ? ok(value as T) : fail('invalid_enum', 'Value is not supported by this contract.', path); }
function taggedId<T extends CanonicalEntityType | 'role'>(value: JsonValue | undefined, type: T, path: string): DomainResult<`${T}:${string}`> { const parsed = identifier(value, path); if (!parsed.ok) return parsed; return parsed.value.startsWith(`${type}:`) && parsed.value.length > type.length + 1 ? ok(parsed.value as `${T}:${string}`) : fail('invalid_entity_id', `ID must use the opaque ${type}:<id> runtime tag.`, path); }
function optionalTagged<T extends CanonicalEntityType>(value: JsonValue | undefined, type: T, path: string): DomainResult<`${T}:${string}` | undefined> { return value === undefined ? ok(undefined) : taggedId(value, type, path); }
function optionalTime(value: JsonValue | undefined, path: string): DomainResult<string | undefined> { if (value === undefined) return ok(undefined); const parsed = timestamp(value, path); return parsed.ok ? ok(parsed.value.canonical) : parsed; }
interface EntityContext { readonly sportId?: `sport:${string}`; readonly competitionId?: `competition:${string}`; readonly eventStartAt?: string }
function parseEntityContext(input: Readonly<Record<string, JsonValue>>, entityType: CanonicalEntityType, path: string): DomainResult<EntityContext> {
  const sportId = optionalTagged(input.sportId, 'sport', `${path}.sportId`); if (!sportId.ok) return sportId;
  const competitionId = optionalTagged(input.competitionId, 'competition', `${path}.competitionId`); if (!competitionId.ok) return competitionId;
  const eventStartAt = optionalTime(input.eventStartAt, `${path}.eventStartAt`); if (!eventStartAt.ok) return eventStartAt;
  const invalid = (message: string, field: string) => fail<EntityContext>('invalid_entity_context', message, `${path}.${field}`);
  if (entityType === 'sport' && (sportId.value !== undefined || competitionId.value !== undefined || eventStartAt.value !== undefined)) return invalid('Sport context forbids parent identities and event time.', sportId.value !== undefined ? 'sportId' : competitionId.value !== undefined ? 'competitionId' : 'eventStartAt');
  if (entityType === 'competition' && (sportId.value === undefined || competitionId.value !== undefined || eventStartAt.value !== undefined)) return invalid('Competition context requires sportId and forbids competitionId and event time.', sportId.value === undefined ? 'sportId' : competitionId.value !== undefined ? 'competitionId' : 'eventStartAt');
  if (entityType === 'participant' && (sportId.value === undefined || eventStartAt.value !== undefined)) return invalid('Participant context requires sportId, permits competitionId, and forbids event time.', sportId.value === undefined ? 'sportId' : 'eventStartAt');
  if (entityType === 'event' && (sportId.value === undefined || competitionId.value === undefined || eventStartAt.value === undefined)) return invalid('Event context requires sportId, competitionId and eventStartAt.', sportId.value === undefined ? 'sportId' : competitionId.value === undefined ? 'competitionId' : 'eventStartAt');
  return ok({ ...(sportId.value ? { sportId: sportId.value } : {}), ...(competitionId.value ? { competitionId: competitionId.value } : {}), ...(eventStartAt.value ? { eventStartAt: eventStartAt.value } : {}) });
}
function optionalText(value: JsonValue | undefined, path: string): DomainResult<string | undefined> { return value === undefined ? ok(undefined) : boundedText(value, path, DOMAIN_REASON_MAX); }
function optionalRefs(value: JsonValue | undefined, path: string): DomainResult<readonly string[] | undefined> { return value === undefined ? ok(undefined) : stringArray(value, path, MAX_ALIAS_CANDIDATES); }

function parseParticipant(value: JsonValue, path: string): DomainResult<CanonicalEventParticipant> { const parsed = record(value, path); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['participantId', 'roleId', 'role', 'roleVersion', 'evidenceRefs'], path); if (!exact.ok) return exact;
  const participantId = taggedId(parsed.value.participantId, 'participant', `${path}.participantId`); if (!participantId.ok) return participantId; const roleId = taggedId(parsed.value.roleId, 'role', `${path}.roleId`); if (!roleId.ok) return roleId;
  const role = enumValue(parsed.value.role, ['home', 'away', 'competitor', 'draw'], `${path}.role`); if (!role.ok) return role; const version = reference(parsed.value.roleVersion, `${path}.roleVersion`, DOMAIN_VERSION_MAX); if (!version.ok) return version; const evidence = stringArray(parsed.value.evidenceRefs, `${path}.evidenceRefs`, MAX_EVIDENCE_REFS); if (!evidence.ok) return evidence;
  return ok({ participantId: participantId.value, roleId: roleId.value, role: role.value, roleVersion: version.value, evidenceRefs: evidence.value }); }

function normalizeTrusted(value: JsonValue): DomainResult<CanonicalIdentity> { const parsed = record(value, '$'); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['contractVersion', 'entityType', 'canonicalId', 'version', 'evidenceRefs', 'sportId', 'competitionId', 'eventStartAt', 'participants'], '$'); if (!exact.ok) return exact;
  if (parsed.value.contractVersion !== CANONICAL_IDENTITY_CONTRACT_VERSION) return fail('unsupported_version', 'Canonical identity contract version is unsupported.', '$.contractVersion'); const entityType = enumValue(parsed.value.entityType, ['sport', 'competition', 'participant', 'event'], '$.entityType'); if (!entityType.ok) return entityType; const canonicalId = taggedId(parsed.value.canonicalId, entityType.value, '$.canonicalId'); if (!canonicalId.ok) return canonicalId;
  const version = reference(parsed.value.version, '$.version', DOMAIN_VERSION_MAX); if (!version.ok) return version; const evidence = stringArray(parsed.value.evidenceRefs, '$.evidenceRefs', MAX_EVIDENCE_REFS); if (!evidence.ok) return evidence; const context = parseEntityContext(parsed.value, entityType.value, '$'); if (!context.ok) return context;
  if (entityType.value !== 'event' && parsed.value.participants !== undefined) return fail('invalid_entity_context', 'Only event identities may declare participants.', '$.participants');
  let participants: CanonicalEventParticipant[] | undefined; if (entityType.value === 'event') { if (!Array.isArray(parsed.value.participants)) return fail('invalid_entity_context', 'Event identity requires participants.', '$.participants'); if (parsed.value.participants.length < 2 || parsed.value.participants.length > MAX_EVENT_PARTICIPANTS) return fail('limit_exceeded', `Event requires 2-${MAX_EVENT_PARTICIPANTS} participants.`, '$.participants'); participants = []; const ids = new Set<string>(), roleIds = new Set<string>(), singletonRoles = new Set<string>(); for (let index = 0; index < parsed.value.participants.length; index += 1) { const item = parseParticipant(parsed.value.participants[index], `$.participants[${index}]`); if (!item.ok) return item; if (ids.has(item.value.participantId)) return fail('duplicate_participant', 'Participant IDs must be unique.', `$.participants[${index}].participantId`, { inputIndex: index }); if (roleIds.has(item.value.roleId)) return fail('duplicate_role', 'Role IDs must be unique.', `$.participants[${index}].roleId`, { inputIndex: index }); if (item.value.role !== 'competitor' && singletonRoles.has(item.value.role)) return fail('duplicate_role_semantic', `Event role ${item.value.role} may appear at most once.`, `$.participants[${index}].role`, { inputIndex: index }); ids.add(item.value.participantId); roleIds.add(item.value.roleId); if (item.value.role !== 'competitor') singletonRoles.add(item.value.role); participants.push(item.value); } }
  return ok({ contractVersion: CANONICAL_IDENTITY_CONTRACT_VERSION, entityType: entityType.value, canonicalId: canonicalId.value as TaggedCanonicalId, version: version.value, evidenceRefs: evidence.value, ...context.value, ...(participants ? { participants } : {}) }); }
export function normalizeCanonicalIdentity(input: unknown): DomainResult<CanonicalIdentity> { const safe = snapshot(input); if (!safe.ok) return safe; const answer = normalizeTrusted(safe.value); if (answer.ok) issuedCanonicalIdentities.add(answer.value); return answer; }

function parseAlias(value: JsonValue, path: string): DomainResult<ProviderAlias> { const parsed = record(value, path); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['contractVersion', 'aliasRef', 'entityType', 'sourceId', 'providerRef', 'externalKey', 'canonicalId', 'historicalCanonicalId', 'sportId', 'competitionId', 'eventStartAt', 'effectiveFrom', 'effectiveTo', 'status', 'evidenceRefs', 'version', 'viableCandidateRefs', 'quarantineReason', 'supersededByAliasRef', 'supersessionReason'], path); if (!exact.ok) return exact;
  if (parsed.value.contractVersion !== ALIAS_CONTRACT_VERSION) return fail('unsupported_version', 'Provider alias version is unsupported.', `${path}.contractVersion`); const aliasRef = reference(parsed.value.aliasRef, `${path}.aliasRef`); if (!aliasRef.ok) return aliasRef; const entityType = enumValue(parsed.value.entityType, ['sport', 'competition', 'participant', 'event'], `${path}.entityType`); if (!entityType.ok) return entityType; const sourceId = identifier(parsed.value.sourceId, `${path}.sourceId`); if (!sourceId.ok) return sourceId; const providerRef = reference(parsed.value.providerRef, `${path}.providerRef`); if (!providerRef.ok) return providerRef; const externalKey = reference(parsed.value.externalKey, `${path}.externalKey`); if (!externalKey.ok) return externalKey;
  const canonicalId = parsed.value.canonicalId === undefined ? ok<TaggedCanonicalId | undefined>(undefined) : taggedId(parsed.value.canonicalId, entityType.value, `${path}.canonicalId`); if (!canonicalId.ok) return canonicalId; const historical = parsed.value.historicalCanonicalId === undefined ? ok<TaggedCanonicalId | undefined>(undefined) : taggedId(parsed.value.historicalCanonicalId, entityType.value, `${path}.historicalCanonicalId`); if (!historical.ok) return historical; const context = parseEntityContext(parsed.value, entityType.value, path); if (!context.ok) return context;
  const from = timestamp(parsed.value.effectiveFrom, `${path}.effectiveFrom`); if (!from.ok) return from; const to = optionalTime(parsed.value.effectiveTo, `${path}.effectiveTo`); if (!to.ok) return to; if (to.value && Date.parse(to.value) <= from.value.milliseconds) return fail('invalid_effective_range', 'Effective end must be after start.', `${path}.effectiveTo`); const status = enumValue(parsed.value.status, ['resolved', 'unresolved', 'ambiguous', 'quarantined', 'superseded'], `${path}.status`); if (!status.ok) return status; const evidence = stringArray(parsed.value.evidenceRefs, `${path}.evidenceRefs`, MAX_EVIDENCE_REFS); if (!evidence.ok) return evidence; const version = reference(parsed.value.version, `${path}.version`, DOMAIN_VERSION_MAX); if (!version.ok) return version; const viable = optionalRefs(parsed.value.viableCandidateRefs, `${path}.viableCandidateRefs`); if (!viable.ok) return viable; const quarantineReason = optionalText(parsed.value.quarantineReason, `${path}.quarantineReason`); if (!quarantineReason.ok) return quarantineReason; const successor = parsed.value.supersededByAliasRef === undefined ? ok<string | undefined>(undefined) : reference(parsed.value.supersededByAliasRef, `${path}.supersededByAliasRef`); if (!successor.ok) return successor; const supersessionReason = optionalText(parsed.value.supersessionReason, `${path}.supersessionReason`); if (!supersessionReason.ok) return supersessionReason;
  const invalid = (message: string) => fail<ProviderAlias>('invalid_alias_state', message, path, { entityRef: aliasRef.value }); if (status.value === 'resolved' && (!canonicalId.value || historical.value || viable.value || quarantineReason.value || successor.value || supersessionReason.value)) return invalid('Resolved alias requires only active canonicalId.'); if (status.value === 'unresolved' && (canonicalId.value || historical.value || viable.value || quarantineReason.value || successor.value || supersessionReason.value)) return invalid('Unresolved alias forbids winner and lifecycle-state fields.'); if (status.value === 'ambiguous' && (canonicalId.value || historical.value || !viable.value || viable.value.length < 2 || quarantineReason.value || successor.value || supersessionReason.value)) return invalid('Ambiguous alias requires multiple viable candidates and forbids a winner.'); if (status.value === 'quarantined' && (canonicalId.value || historical.value || !quarantineReason.value || successor.value || supersessionReason.value)) return invalid('Quarantined alias requires reason/evidence and forbids a winner.'); if (status.value === 'superseded' && (canonicalId.value || !historical.value || viable.value || quarantineReason.value || !successor.value || !supersessionReason.value)) return invalid('Superseded alias requires historical mapping, successor and reason, and forbids active canonicalId.');
  return ok({ contractVersion: ALIAS_CONTRACT_VERSION, aliasRef: aliasRef.value, entityType: entityType.value, sourceId: sourceId.value, providerRef: providerRef.value, externalKey: externalKey.value, ...(canonicalId.value ? { canonicalId: canonicalId.value } : {}), ...(historical.value ? { historicalCanonicalId: historical.value } : {}), ...context.value, effectiveFrom: from.value.canonical, ...(to.value ? { effectiveTo: to.value } : {}), status: status.value, evidenceRefs: evidence.value, version: version.value, ...(viable.value ? { viableCandidateRefs: [...viable.value].sort() } : {}), ...(quarantineReason.value ? { quarantineReason: quarantineReason.value } : {}), ...(successor.value ? { supersededByAliasRef: successor.value } : {}), ...(supersessionReason.value ? { supersessionReason: supersessionReason.value } : {}) }); }

function sameScope(a: ProviderAlias, b: ProviderAlias): boolean { return a.entityType === b.entityType && a.sourceId === b.sourceId && a.providerRef === b.providerRef && a.externalKey === b.externalKey && a.sportId === b.sportId && a.competitionId === b.competitionId && a.eventStartAt === b.eventStartAt; }
function overlaps(a: ProviderAlias, b: ProviderAlias): boolean { const ae = a.effectiveTo ? Date.parse(a.effectiveTo) : Infinity, be = b.effectiveTo ? Date.parse(b.effectiveTo) : Infinity; return Date.parse(a.effectiveFrom) < be && Date.parse(b.effectiveFrom) < ae; }
function validateSetTrusted(value: JsonValue, path: string): DomainResult<AliasSet> { const parsed = record(value, path); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['contractVersion', 'aliases'], path); if (!exact.ok) return exact; if (parsed.value.contractVersion !== ALIAS_SET_CONTRACT_VERSION) return fail('unsupported_version', 'Alias-set version is unsupported.', `${path}.contractVersion`); if (!Array.isArray(parsed.value.aliases)) return fail('invalid_input', 'Aliases must be an array.', `${path}.aliases`); if (!parsed.value.aliases.length || parsed.value.aliases.length > MAX_ALIASES) return fail('limit_exceeded', `Alias set requires 1-${MAX_ALIASES} aliases.`, `${path}.aliases`, { metadata: { limit: MAX_ALIASES, actual: parsed.value.aliases.length } }); const aliases: ProviderAlias[] = [], byRef = new Map<string, ProviderAlias>();
  for (let index = 0; index < parsed.value.aliases.length; index += 1) { const item = parseAlias(parsed.value.aliases[index], `${path}.aliases[${index}]`); if (!item.ok) return item; if (byRef.has(item.value.aliasRef)) return fail('duplicate_alias_reference', 'Alias references must be unique.', `${path}.aliases[${index}].aliasRef`, { inputIndex: index }); if (aliases.length && !sameScope(aliases[0], item.value)) return fail('alias_scope_conflict', 'Alias lifecycle set must share exact scope.', `${path}.aliases[${index}]`, { inputIndex: index }); byRef.set(item.value.aliasRef, item.value); aliases.push(item.value); }
  for (let a = 0; a < aliases.length; a += 1) for (let b = a + 1; b < aliases.length; b += 1) if (overlaps(aliases[a], aliases[b])) return fail('overlapping_alias_interval', 'Alias intervals must not overlap.', `${path}.aliases[${b}]`, { inputIndex: b });
  for (const item of aliases) if (item.status === 'superseded') { if (item.supersededByAliasRef === item.aliasRef) return fail('alias_supersession_cycle', 'Alias cannot supersede itself.', path, { entityRef: item.aliasRef }); const target = byRef.get(item.supersededByAliasRef!); if (!target) return fail('missing_alias_successor', 'Supersession target must exist.', path, { entityRef: item.supersededByAliasRef }); if (!item.effectiveTo || item.effectiveTo !== target.effectiveFrom) return fail('invalid_alias_transition', 'Successor must begin exactly at predecessor end.', path, { entityRef: item.aliasRef }); }
  for (const item of aliases) { const seen = new Set<string>(); let cursor: ProviderAlias | undefined = item, depth = 0; while (cursor?.status === 'superseded') { if (seen.has(cursor.aliasRef)) return fail('alias_supersession_cycle', 'Supersession chain contains a cycle.', path, { entityRef: cursor.aliasRef }); seen.add(cursor.aliasRef); cursor = byRef.get(cursor.supersededByAliasRef!); if (++depth > MAX_ALIAS_CHAIN_DEPTH) return fail('alias_chain_limit_exceeded', 'Supersession chain exceeds limit.', path); } }
  return ok({ contractVersion: ALIAS_SET_CONTRACT_VERSION, aliases }); }
export function validateAliasSet(input: unknown): DomainResult<AliasSet> { const safe = snapshot(input); return safe.ok ? validateSetTrusted(safe.value, '$') : safe; }

function parseCandidate(value: JsonValue, path: string): DomainResult<AliasCandidate> { const parsed = record(value, path); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['candidateRef', 'canonicalId', 'entityType', 'sourceId', 'providerRef', 'externalKey', 'sportId', 'competitionId', 'eventStartAt', 'evidenceRefs', 'evidenceKind'], path); if (!exact.ok) return exact; const candidateRef = reference(parsed.value.candidateRef, `${path}.candidateRef`); if (!candidateRef.ok) return candidateRef; const entityType = enumValue(parsed.value.entityType, ['sport', 'competition', 'participant', 'event'], `${path}.entityType`); if (!entityType.ok) return entityType; const canonicalId = taggedId(parsed.value.canonicalId, entityType.value, `${path}.canonicalId`); if (!canonicalId.ok) return canonicalId; const sourceId = identifier(parsed.value.sourceId, `${path}.sourceId`); if (!sourceId.ok) return sourceId; const providerRef = reference(parsed.value.providerRef, `${path}.providerRef`); if (!providerRef.ok) return providerRef; const externalKey = reference(parsed.value.externalKey, `${path}.externalKey`); if (!externalKey.ok) return externalKey; const context = parseEntityContext(parsed.value, entityType.value, path); if (!context.ok) return context; const evidence = stringArray(parsed.value.evidenceRefs, `${path}.evidenceRefs`, MAX_EVIDENCE_REFS); if (!evidence.ok) return evidence; const kind = enumValue(parsed.value.evidenceKind, ['exact_source_key', 'display_name_similarity'], `${path}.evidenceKind`); if (!kind.ok) return kind; return ok({ candidateRef: candidateRef.value, canonicalId: canonicalId.value as TaggedCanonicalId, entityType: entityType.value, sourceId: sourceId.value, providerRef: providerRef.value, externalKey: externalKey.value, ...context.value, evidenceRefs: evidence.value, evidenceKind: kind.value }); }
function candidateMatches(alias: ProviderAlias, item: AliasCandidate): boolean { return alias.entityType === item.entityType && alias.sourceId === item.sourceId && alias.providerRef === item.providerRef && alias.externalKey === item.externalKey && alias.sportId === item.sportId && alias.competitionId === item.competitionId && alias.eventStartAt === item.eventStartAt; }

export function resolveProviderAlias(input: unknown): DomainResult<AliasResolution> { const safe = snapshot(input); if (!safe.ok) return safe; const root = record(safe.value, '$'); if (!root.ok) return root; const exact = shape(root.value, ['aliasSet', 'candidates', 'asOf', 'policy'], '$'); if (!exact.ok) return exact; if (!isRecord(root.value.policy) || Object.keys(root.value.policy).length !== 2 || root.value.policy.id !== ALIAS_RESOLUTION_POLICY.id || root.value.policy.version !== ALIAS_RESOLUTION_POLICY.version) return fail('unsupported_policy', 'Only alias-set exact policy v2 is supported.', '$.policy'); const aliasSet = validateSetTrusted(root.value.aliasSet, '$.aliasSet'); if (!aliasSet.ok) return aliasSet; const asOf = timestamp(root.value.asOf, '$.asOf'); if (!asOf.ok) return asOf; const effective = aliasSet.value.aliases.filter((item) => asOf.value.milliseconds >= Date.parse(item.effectiveFrom) && (!item.effectiveTo || asOf.value.milliseconds < Date.parse(item.effectiveTo))); if (effective.length !== 1) return fail(effective.length ? 'overlapping_alias_interval' : 'alias_not_effective', effective.length ? 'Multiple aliases are effective.' : 'No alias is effective.', '$.asOf'); const alias = effective[0]; if (!Array.isArray(root.value.candidates)) return fail('invalid_input', 'Candidates must be an array.', '$.candidates'); if (root.value.candidates.length > MAX_ALIAS_CANDIDATES) return fail('limit_exceeded', 'Candidate limit exceeded.', '$.candidates'); const candidates: AliasCandidate[] = [], refs = new Set<string>(), ids = new Set<string>();
  for (let index = 0; index < root.value.candidates.length; index += 1) { const item = parseCandidate(root.value.candidates[index], `$.candidates[${index}]`); if (!item.ok) return item; if (refs.has(item.value.candidateRef) || ids.has(item.value.canonicalId)) return fail('duplicate_candidate', 'Candidate references and IDs must be unique.', `$.candidates[${index}]`, { inputIndex: index }); if (!candidateMatches(alias, item.value)) return fail('identity_conflict', 'Candidate conflicts with alias scope.', `$.candidates[${index}]`); refs.add(item.value.candidateRef); ids.add(item.value.canonicalId); candidates.push(item.value); }
  const exactCandidates = candidates.filter((item) => item.evidenceKind === 'exact_source_key'), sortedRefs = exactCandidates.map((item) => item.candidateRef).sort(), evidenceRefs = [...new Set([...alias.evidenceRefs, ...candidates.flatMap((item) => item.evidenceRefs)])].sort(); const base = { contractVersion: 'alias-resolution-v2' as const, alias, aliasSet: aliasSet.value, policy: ALIAS_RESOLUTION_POLICY, evaluatedAt: asOf.value.canonical, evidenceRefs };
  let answer: DomainResult<AliasResolution>;
  if (alias.status === 'resolved') { if (exactCandidates.length !== 1 || exactCandidates[0].canonicalId !== alias.canonicalId) return fail('alias_state_contradiction', 'Resolved alias requires exactly one exact candidate matching stored ID.', '$.candidates'); answer = ok({ ...base, status: 'resolved', reason: 'stored_resolved_mapping_confirmed', canonicalId: alias.canonicalId, candidateRefs: sortedRefs }); }
  else if (alias.status === 'unresolved') { if (exactCandidates.length) return fail('alias_state_contradiction', 'Unresolved alias cannot conceal a winner.', '$.candidates'); answer = ok({ ...base, status: 'unresolved', reason: candidates.length ? 'similarity_evidence_cannot_resolve' : 'no_candidate', candidateRefs: [] }); }
  else if (alias.status === 'ambiguous') { if (exactCandidates.length < 2 || JSON.stringify(sortedRefs) !== JSON.stringify(alias.viableCandidateRefs)) return fail('alias_state_contradiction', 'Ambiguous candidates must match stored viable set.', '$.candidates'); answer = ok({ ...base, status: 'ambiguous', reason: 'multiple_exact_candidates', candidateRefs: sortedRefs }); }
  else if (alias.status === 'quarantined') answer = ok({ ...base, status: 'quarantined', reason: alias.quarantineReason!, candidateRefs: sortedRefs });
  else answer = ok({ ...base, status: 'superseded', reason: alias.supersessionReason!, historicalCanonicalId: alias.historicalCanonicalId, candidateRefs: [] });
  if (answer.ok) issuedAliasResolutions.add(answer.value); return answer; }

export function issueResultMappingDecision(input: unknown, participantResolution: AliasResolution, eventResolution: AliasResolution, eventIdentity: CanonicalIdentity): DomainResult<ResolverIssuedResultMappingDecision> {
  for (const [name, resolution] of [['participantResolution', participantResolution], ['eventResolution', eventResolution]] as const) if (typeof resolution !== 'object' || resolution === null || !issuedAliasResolutions.has(resolution)) return fail('untrusted_alias_resolution', 'Mapping authority requires resolver-issued alias resolutions from this runtime.', `$.${name}`);
  if (!issuedCanonicalIdentities.has(eventIdentity) || eventIdentity.entityType !== 'event' || !eventIdentity.participants) return fail('untrusted_canonical_identity', 'Mapping authority requires a canonical identity issued in this runtime.', '$.eventIdentity');
  if (participantResolution.status !== 'resolved' || participantResolution.alias.status !== 'resolved' || participantResolution.alias.entityType !== 'participant' || !participantResolution.canonicalId?.startsWith('participant:') || participantResolution.reason !== 'stored_resolved_mapping_confirmed' || eventResolution.status !== 'resolved' || eventResolution.alias.status !== 'resolved' || eventResolution.alias.entityType !== 'event' || eventResolution.reason !== 'stored_resolved_mapping_confirmed' || eventResolution.canonicalId !== eventIdentity.canonicalId) return fail('unresolved_mapping_evidence', 'Only active exact participant and event resolutions can issue mapping authority.', '$.resolution');
  const safe = snapshot(input); if (!safe.ok) return safe; const root = record(safe.value, '$'); if (!root.ok) return root; const exact = shape(root.value, ['decisionRef', 'providerRoleRef', 'roleId', 'role'], '$'); if (!exact.ok) return exact;
  const decisionRef = reference(root.value.decisionRef, '$.decisionRef'); if (!decisionRef.ok) return decisionRef; const providerRoleRef = reference(root.value.providerRoleRef, '$.providerRoleRef'); if (!providerRoleRef.ok) return providerRoleRef; const roleId = taggedId(root.value.roleId, 'role', '$.roleId'); if (!roleId.ok) return roleId; const role = enumValue(root.value.role, ['home', 'away', 'competitor', 'draw'], '$.role'); if (!role.ok) return role;
  if (!participantResolution.alias.sportId || !participantResolution.alias.competitionId || participantResolution.alias.sourceId !== eventResolution.alias.sourceId || participantResolution.alias.providerRef !== eventResolution.alias.providerRef || participantResolution.alias.sportId !== eventIdentity.sportId || participantResolution.alias.competitionId !== eventIdentity.competitionId || eventResolution.alias.sportId !== eventIdentity.sportId || eventResolution.alias.competitionId !== eventIdentity.competitionId) return fail('identity_conflict', 'Participant and event resolver scopes must match the canonical event.', '$.resolution'); const participant = eventIdentity.participants.find((item) => item.participantId === participantResolution.canonicalId); if (!participant || participant.roleId !== roleId.value || participant.role !== role.value) return fail('identity_conflict', 'Resolved participant role must exist in the canonical event.', '$.role');
  const answer = ok({ contractVersion: 'resolver-issued-result-mapping-v1' as const, decisionRef: decisionRef.value, resolverContractVersion: participantResolution.contractVersion, resolverPolicy: participantResolution.policy, aliasContractVersion: participantResolution.alias.contractVersion, aliasRef: participantResolution.alias.aliasRef, aliasVersion: participantResolution.alias.version, aliasStatus: 'resolved' as const, effectiveFrom: participantResolution.alias.effectiveFrom, ...(participantResolution.alias.effectiveTo ? { effectiveTo: participantResolution.alias.effectiveTo } : {}), evaluatedAt: participantResolution.evaluatedAt, supportingEvidenceRefs: [participantResolution.alias.aliasRef, eventResolution.alias.aliasRef].sort(), sourceId: participantResolution.alias.sourceId, providerRef: participantResolution.alias.providerRef, providerEventRef: eventResolution.alias.externalKey, providerParticipantRef: participantResolution.alias.externalKey, providerRoleRef: providerRoleRef.value, sportId: participantResolution.alias.sportId, competitionId: participantResolution.alias.competitionId, eventId: eventIdentity.canonicalId as `event:${string}`, participantId: participantResolution.canonicalId as `participant:${string}`, roleId: roleId.value, role: role.value, identityContractVersion: eventIdentity.contractVersion, resolutionStatus: 'resolved' as const, resolutionKind: 'exact_source_key' as const });
  if (answer.ok) issuedResultMappingDecisions.add(answer.value); return answer;
}
export function isResolverIssuedResultMappingDecision(value: unknown): value is ResolverIssuedResultMappingDecision { return typeof value === 'object' && value !== null && issuedResultMappingDecisions.has(value); }

export type { DomainError, DomainResult };
