import { canonicalJsonText } from './canonical-json.ts';
import { deepFreeze, fail, ok, snapshot, type DomainResult } from './domain-validation.ts';
import { RECORD_LIMITS, type AuthenticatedIntelligenceRecord } from './authenticated-record.ts';

export interface D1PreparedStatementLike{bind(...values:unknown[]):D1PreparedStatementLike;first<T=Record<string,unknown>>():Promise<T|null>;all<T=Record<string,unknown>>():Promise<{results:T[]}>}
export interface D1ResultLike{readonly success:boolean;readonly meta?:Readonly<{changes?:number}>}
export interface D1DatabaseLike{prepare(query:string):D1PreparedStatementLike;batch(statements:D1PreparedStatementLike[]):Promise<D1ResultLike[]>}
export interface AppendRequest{readonly record:AuthenticatedIntelligenceRecord;readonly idempotencyKey:string;readonly auditEventId:string;readonly appendedAt:string}
export interface AppendResult{readonly status:'appended'|'idempotent';readonly recordId:string;readonly streamId:string}
export interface SnapshotRecord{readonly record:AuthenticatedIntelligenceRecord;readonly rightsSchedule:unknown;readonly retention:Readonly<{status:string;projectDeleteAfter?:string;hardSourceDeleteAfter?:string}>;readonly keyMetadata:Readonly<{algorithm:string;status:string;activatesAt:string;verifyUntil?:string}>;readonly parents:readonly string[]}
export interface AuthoritativeIntelligenceSnapshot{readonly version:'authoritative-intelligence-snapshot/1';readonly snapshotId:string;readonly environmentId:string;readonly streamId:string;readonly recordType:string;readonly selectedRecordId:string;readonly currentHeadId:string;readonly headRevision:number;readonly records:readonly SnapshotRecord[]}
export interface IntelligenceRecordRepository{append(request:AppendRequest):Promise<DomainResult<AppendResult>>;readAuthoritativeSnapshot(environmentId:string,streamId:string,recordType:string,recordId:string):Promise<DomainResult<AuthoritativeIntelligenceSnapshot>>}
const IDEMPOTENCY=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;type Existing={record_id:string;content_hash:string;authentication_tag:string;stream_id:string};

const SNAPSHOT_SQL=`WITH RECURSIVE ancestry(record_id,depth) AS (
 SELECT ?1,0 UNION ALL SELECT p.parent_record_id,a.depth+1 FROM ancestry a JOIN intelligence_record_parents p ON p.environment_id=?2 AND p.child_record_id=a.record_id WHERE a.depth<16
), rows AS (
 SELECT r.*,h.current_record_id,h.revision,rs.schedule_jcs,km.algorithm key_algorithm,km.status key_status,km.activates_at key_activates_at,km.verify_until key_verify_until,
 (SELECT re.status FROM intelligence_retention_events re WHERE re.environment_id=r.environment_id AND re.record_id=r.record_id ORDER BY re.occurred_at DESC,re.event_id DESC LIMIT 1) retention_status,
 (SELECT re.project_delete_after FROM intelligence_retention_events re WHERE re.environment_id=r.environment_id AND re.record_id=r.record_id ORDER BY re.occurred_at DESC,re.event_id DESC LIMIT 1) retention_project_delete_after,
 (SELECT re.hard_source_delete_after FROM intelligence_retention_events re WHERE re.environment_id=r.environment_id AND re.record_id=r.record_id ORDER BY re.occurred_at DESC,re.event_id DESC LIMIT 1) retention_hard_source_delete_after,
 (SELECT group_concat(parent_record_id,'|') FROM (SELECT parent_record_id FROM intelligence_record_parents p WHERE p.environment_id=r.environment_id AND p.child_record_id=r.record_id ORDER BY ordinal)) parent_ids
 FROM ancestry a JOIN authenticated_intelligence_records r ON r.environment_id=?2 AND r.record_id=a.record_id JOIN intelligence_record_commits c ON c.environment_id=r.environment_id AND c.record_id=r.record_id
 JOIN intelligence_stream_heads h ON h.environment_id=r.environment_id AND h.stream_id=?3 AND h.record_type=?4 JOIN intelligence_rights_schedules rs ON rs.environment_id=r.environment_id AND rs.schedule_id=r.rights_schedule_id
 JOIN intelligence_key_metadata km ON km.environment_id=r.environment_id AND km.key_id=r.key_id WHERE r.stream_id=?3 AND r.record_type=?4
) SELECT * FROM rows ORDER BY record_id`;

export class D1IntelligenceRecordRepository implements IntelligenceRecordRepository{
 private readonly db:D1DatabaseLike;constructor(db:D1DatabaseLike){this.db=db}
 async append(request:AppendRequest):Promise<DomainResult<AppendResult>>{
  const safe=snapshot(request);if(!safe.ok)return fail('invalid_input','Append request failed bounded inspection.',safe.error.path);const clean=safe.value as unknown as AppendRequest;if(!IDEMPOTENCY.test(clean.idempotencyKey))return fail('invalid_idempotency_key','Idempotency key is invalid.','$.idempotencyKey');const r=clean.record;request=clean;let existing:Existing|null;try{existing=await this.db.prepare('SELECT record_id,content_hash,authentication_tag,stream_id FROM authenticated_intelligence_records WHERE environment_id=? AND idempotency_key=?').bind(r.environmentId,request.idempotencyKey).first<Existing>()}catch{return fail('database_failure','Database read failed.','$.idempotencyKey')}
  if(existing)return existing.content_hash===r.contentHash&&existing.authentication_tag===r.authenticationTag&&existing.record_id===r.recordId?ok(deepFreeze({status:'idempotent',recordId:existing.record_id,streamId:existing.stream_id})):fail('idempotency_collision','Idempotency key has different content.','$.idempotencyKey');
  let payloadJcs:string,headerJcs:string;try{payloadJcs=canonicalJsonText(r.payload,RECORD_LIMITS.maxPayloadBytes);headerJcs=canonicalJsonText(Object.fromEntries(Object.entries(r).filter(([k])=>!['payload','contentHash','authenticationTag'].includes(k))))}catch{return fail('invalid_input','Record serialization failed.','$.record')}
  const first=r.parentRefs[0]??null,statements=[this.db.prepare('INSERT INTO authenticated_intelligence_records(environment_id,record_id,stream_id,record_type,schema_version,contract_version,rights_schedule_id,key_id,idempotency_key,content_hash,authentication_tag,header_jcs,payload_jcs,declared_parent_count,parent_head_id,corrects_record_id,issued_at,validated_at,project_delete_after,hard_source_delete_after,indefinite_basis) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(r.environmentId,r.recordId,r.streamId,r.recordType,r.schemaVersion,r.contractVersion,r.rightsScheduleId,r.keyId,request.idempotencyKey,r.contentHash,r.authenticationTag,headerJcs,payloadJcs,r.parentRefs.length,first,r.correctsRecordId??null,r.issuedAt,r.validatedAt,r.projectDeleteAfter??null,r.hardSourceDeleteAfter??null,r.indefiniteBasis??null),...r.parentRefs.map((parent,ordinal)=>this.db.prepare('INSERT INTO intelligence_record_parents(environment_id,child_record_id,child_stream_id,child_record_type,parent_record_id,parent_stream_id,parent_record_type,ordinal) VALUES(?,?,?,?,?,?,?,?)').bind(r.environmentId,r.recordId,r.streamId,r.recordType,parent,r.streamId,r.recordType,ordinal)),this.db.prepare('INSERT INTO intelligence_record_commits(environment_id,record_id,committed_at,commit_version) VALUES(?,?,?,?)').bind(r.environmentId,r.recordId,request.appendedAt,'intelligence-record-commit/1'),first===null?this.db.prepare('INSERT INTO intelligence_stream_heads(environment_id,stream_id,record_type,current_record_id,revision) VALUES(?,?,?,?,1)').bind(r.environmentId,r.streamId,r.recordType,r.recordId):this.db.prepare('UPDATE intelligence_stream_heads SET current_record_id=?,revision=revision+1 WHERE environment_id=? AND stream_id=? AND record_type=? AND current_record_id=?').bind(r.recordId,r.environmentId,r.streamId,r.recordType,first),this.db.prepare('INSERT INTO intelligence_retention_events(environment_id,event_id,record_id,status,project_delete_after,hard_source_delete_after,occurred_at,metadata_jcs) VALUES(?,?,?,?,?,?,?,?)').bind(r.environmentId,`${request.auditEventId}:retention`,r.recordId,'retained',r.projectDeleteAfter??null,r.hardSourceDeleteAfter??null,request.appendedAt,'{}'),this.db.prepare('INSERT INTO intelligence_audit_events(environment_id,event_id,event_type,record_id,occurred_at,metadata_jcs) VALUES(?,?,?,?,?,?)').bind(r.environmentId,request.auditEventId,'record_appended',r.recordId,request.appendedAt,canonicalJsonText({streamId:r.streamId,recordType:r.recordType}))];
  try{await this.db.batch(statements);return ok(deepFreeze({status:'appended',recordId:r.recordId,streamId:r.streamId}))}catch(error){const message=error instanceof Error?error.message:'';if(message.includes('head_scope')||message.includes('single_successor'))return fail('head_conflict','Stream head changed or would fork.','$.record.parentRefs');if(message.includes('incomplete_record'))return fail('parent_invalid','Declared parent set is incomplete.','$.record.parentRefs');if(message.includes('FOREIGN KEY'))return fail('missing_parent_or_rights','Required metadata or parent is missing.','$.record');if(message.includes('UNIQUE'))return fail('duplicate_record','Immutable identity or content exists.','$.record');return fail('database_failure','Atomic database append failed.','$.record')}
 }
 async readAuthoritativeSnapshot(environmentId:string,streamId:string,recordType:string,recordId:string):Promise<DomainResult<AuthoritativeIntelligenceSnapshot>>{
  let rows:Record<string,unknown>[];try{rows=(await this.db.prepare(SNAPSHOT_SQL).bind(recordId,environmentId,streamId,recordType).all()).results}catch{return fail('database_failure','Authoritative snapshot read failed.','$')};if(rows.length===0)return fail('snapshot_not_found','No authoritative snapshot was found.','$');if(rows.length>17)return fail('snapshot_limit_exceeded','Snapshot exceeds ancestry limit.','$');
  const first=rows[0],records=rows.map(row=>({record:{...JSON.parse(String(row.header_jcs)),payload:JSON.parse(String(row.payload_jcs)),contentHash:String(row.content_hash),authenticationTag:String(row.authentication_tag)}as AuthenticatedIntelligenceRecord,rightsSchedule:JSON.parse(String(row.schedule_jcs)),retention:{status:String(row.retention_status),...(row.retention_project_delete_after?{projectDeleteAfter:String(row.retention_project_delete_after)}:{}),...(row.retention_hard_source_delete_after?{hardSourceDeleteAfter:String(row.retention_hard_source_delete_after)}:{})},keyMetadata:{algorithm:String(row.key_algorithm),status:String(row.key_status),activatesAt:String(row.key_activates_at),...(row.key_verify_until?{verifyUntil:String(row.key_verify_until)}:{})},parents:row.parent_ids?String(row.parent_ids).split('|'):[]}));
  const ids=new Set(records.map(x=>x.record.recordId));for(const item of records)for(const parent of item.parents)if(!ids.has(parent))return fail('parent_missing','Snapshot omits required ancestry.','$.records');return ok(deepFreeze({version:'authoritative-intelligence-snapshot/1',snapshotId:`head:${String(first.current_record_id)}:revision:${String(first.revision)}`,environmentId,streamId,recordType,selectedRecordId:recordId,currentHeadId:String(first.current_record_id),headRevision:Number(first.revision),records}));
 }
}
