import { canonicalJsonText } from './canonical-json.ts';
import { deepFreeze, fail, ok, type DomainResult } from './domain-validation.ts';
import { normalizeMarketObservation, type NormalizedMarketSnapshot } from './market-observation.ts';
import { verifyAuthenticatedRecord, type AuthenticatedIntelligenceRecord, type IntelligenceVerificationKeyProvider, type VerificationKey } from './authenticated-record.ts';
import { validateRightsSchedule, type RightsSchedule } from './intelligence-rights.ts';
import type { AuthoritativeIntelligenceSnapshot, IntelligenceRecordRepository } from './intelligence-repository.ts';

export type QuarantineReason='hash_mismatch'|'mac_mismatch'|'wrong_environment'|'unknown_key'|'revoked_key'|'key_period_invalid'|'rights_expired'|'deletion_required'|'parent_missing'|'parent_invalid'|'rollback_detected'|'unsupported_version'|'unsupported_record_type'|'domain_invalid'|'provider_or_port_failure'|'malformed_envelope';
export interface QuarantinePlan{readonly version:'intelligence-quarantine-plan/1';readonly environmentId:string;readonly recordId?:string;readonly reason:QuarantineReason;readonly createdAt:string;readonly metadata:Readonly<{failureCode:string;failurePath:string}>}
export interface AuditEvent{readonly version:'intelligence-audit-event/1';readonly eventId:string;readonly eventType:'record_rehydrated'|'record_quarantined'|'deletion_planned'|'restore_reconciled';readonly environmentId:string;readonly recordId?:string;readonly occurredAt:string;readonly metadata:Readonly<Record<string,string>>}
export interface ExternalDeletionLedger{getDeletionStates(environmentId:string,recordIds:readonly string[]):Promise<Readonly<Record<string,'active'|'deleted'>>>;recordContractualDeletion(input:Readonly<{environmentId:string;recordId:string;deletedAt:string;basis:string}>):Promise<void>}
export interface PostRestoreReconciliationPort{reconcileBeforeServing(input:Readonly<{environmentId:string;restoredAt:string;snapshotId:string}>):Promise<Readonly<{status:'safe'|'blocked';checkedRecords:number}>>}
export interface BackupExpiry{readonly backupRef:string;readonly expiresAt:string;readonly includesThrough:string}
export interface LegalHoldDecision{readonly version:'legal-hold-authorization/1';readonly authorityClass:'authorized_legal_hold';readonly authorityRef:string;readonly approverRef:string;readonly environmentId:string;readonly recordId:string;readonly scheduleId:string;readonly issuedAt:string;readonly expiresAt:string;readonly scope:'project_deletion_only';readonly status:'active'|'released'}
export interface LegalHoldAuthority{getDecision(environmentId:string,recordId:string,scheduleId:string,at:string):Promise<LegalHoldDecision|undefined>}
export interface DeletionPlan{readonly version:'intelligence-deletion-plan/1';readonly environmentId:string;readonly recordId:string;readonly action:'retain'|'delete';readonly executeAfter?:string;readonly basis:string;readonly legalHoldRef?:string}

export async function planDeletion(record:AuthenticatedIntelligenceRecord,schedule:RightsSchedule,status:string,now:string,holds:LegalHoldAuthority):Promise<DomainResult<DeletionPlan>>{
 let hold:LegalHoldDecision|undefined;try{hold=await holds.getDecision(record.environmentId,record.recordId,schedule.scheduleId,now)}catch{return fail('provider_or_port_failure','Legal-hold authority failed.','$')};const hard=record.hardSourceDeleteAfter,project=record.projectDeleteAfter,hardDue=!!hard&&Date.parse(now)>=Date.parse(hard),forced=status==='delete_required'||status==='deleted'||status==='provider_exit'||hardDue;
 const valid=!!hold&&schedule.legalHoldHandling==='honour_valid_hold'&&hold.version==='legal-hold-authorization/1'&&hold.authorityClass==='authorized_legal_hold'&&hold.environmentId===record.environmentId&&hold.recordId===record.recordId&&hold.scheduleId===schedule.scheduleId&&hold.scope==='project_deletion_only'&&hold.status==='active'&&Date.parse(hold.issuedAt)<=Date.parse(now)&&Date.parse(now)<Date.parse(hold.expiresAt);
 if(forced)return ok(deepFreeze({version:'intelligence-deletion-plan/1',environmentId:record.environmentId,recordId:record.recordId,action:'delete',...(hard?{executeAfter:hard}:{}),basis:status==='provider_exit'?'provider_exit':'hard_source_rights_or_required_deletion'}));if(valid&&hold&&project&&Date.parse(now)>=Date.parse(project))return ok(deepFreeze({version:'intelligence-deletion-plan/1',environmentId:record.environmentId,recordId:record.recordId,action:'retain',basis:'authorized_project_deletion_pause',legalHoldRef:hold.authorityRef}));const due=!!project&&Date.parse(now)>=Date.parse(project);return ok(deepFreeze({version:'intelligence-deletion-plan/1',environmentId:record.environmentId,recordId:record.recordId,action:due?'delete':'retain',...(project?{executeAfter:project}:{}),basis:due?'project_retention_expired':'within_source_and_project_rights'}));
}

export type RehydratedIntelligence=Readonly<{record:AuthenticatedIntelligenceRecord;capability:NormalizedMarketSnapshot;audit:AuditEvent;snapshotId:string}>;
export type RehydrationResult=DomainResult<RehydratedIntelligence>|Readonly<{ok:false;error:Readonly<{code:'quarantine_required';message:string;path:string;metadata:Readonly<{plan:QuarantinePlan}>}>}>;
const MAP:Readonly<Record<string,QuarantineReason>>=Object.freeze({hash_mismatch:'hash_mismatch',mac_mismatch:'mac_mismatch',wrong_environment:'wrong_environment',unknown_key:'unknown_key',revoked_key:'revoked_key',key_period_invalid:'key_period_invalid',unsupported_version:'unsupported_version',unsupported_record_type:'unsupported_record_type',domain_invalid:'domain_invalid',parent_missing:'parent_missing',parent_invalid:'parent_invalid',snapshot_not_found:'rollback_detected',snapshot_bookmark_mismatch:'rollback_detected',database_failure:'provider_or_port_failure',key_provider_failure:'provider_or_port_failure',cryptographic_failure:'provider_or_port_failure'});
function quarantine(environmentId:string,recordId:string|undefined,now:string,code:string,path:string):RehydrationResult{const reason=MAP[code]??'malformed_envelope',plan=deepFreeze({version:'intelligence-quarantine-plan/1' as const,environmentId,...(recordId?{recordId}:{}),reason,createdAt:now,metadata:{failureCode:code,failurePath:path}});canonicalJsonText(plan,2048);return{ok:false,error:deepFreeze({code:'quarantine_required' as const,message:'Record requires quarantine; history is not repaired.',path,metadata:{plan}})}}

function validateSnapshotShape(snapshot:AuthoritativeIntelligenceSnapshot,environmentId:string,recordId:string):DomainResult<true>{if(snapshot.environmentId!==environmentId||snapshot.selectedRecordId!==recordId)return fail('snapshot_bookmark_mismatch','Snapshot identity does not match request.','$');if(snapshot.currentHeadId!==recordId)return fail('rollback_detected','Selected record is not current.','$.currentHeadId');if(snapshot.records.length<1||snapshot.records.length>17)return fail('parent_invalid','Snapshot row count is invalid.','$.records');const ids=new Set<string>();for(const row of snapshot.records){const r=row.record;if(ids.has(r.recordId))return fail('parent_invalid','Cycle or duplicate ancestry detected.','$.records');ids.add(r.recordId);if(r.environmentId!==environmentId||r.streamId!==snapshot.streamId||r.recordType!==snapshot.recordType||row.parents.length!==r.parentRefs.length||row.parents.some((p,i)=>p!==r.parentRefs[i]))return fail('parent_invalid','Ancestry scope or edges are inconsistent.','$.records')}for(const row of snapshot.records)for(const parent of row.parents)if(!ids.has(parent))return fail('parent_missing','Required ancestor is absent.','$.records');return ok(true)}
function revalidatePersistedMarket(payload:unknown){if(typeof payload!=='object'||payload===null||Array.isArray(payload))return normalizeMarketObservation(payload);const value=payload as Record<string,unknown>;if(value.contractVersion!=='market-observation-v1'||!Array.isArray(value.outcomes))return normalizeMarketObservation(payload);return normalizeMarketObservation({sourceEnvelope:value.sourceEnvelope,sportId:value.sportId,competitionId:value.competitionId,eventId:value.eventId,marketId:value.marketId,eventStartAt:value.eventStartAt,asOf:value.asOf,freshnessPolicy:value.freshnessPolicy,completeness:value.completeness,marketAvailability:value.marketAvailability,outcomes:value.outcomes.map(item=>{const outcome=item as Record<string,unknown>;return{outcomeId:outcome.outcomeId,...(outcome.decimalOdds!==undefined?{decimalOdds:outcome.decimalOdds}:{}),availability:outcome.availability,observationRef:outcome.observationRef,...(outcome.sourceSequence!==undefined?{sourceSequence:outcome.sourceSequence}:{}),identity:{sportId:value.sportId,competitionId:value.competitionId,eventId:value.eventId,marketId:value.marketId,outcomeId:outcome.outcomeId}}})})}

export async function rehydrateIntelligenceRecord(request:Readonly<{environmentId:string;streamId:string;recordType:string;recordId:string;expectedSnapshotId?:string}>,context:Readonly<{now:string;keys:IntelligenceVerificationKeyProvider;repository:IntelligenceRecordRepository;deletionLedger:ExternalDeletionLedger;auditEventId:string}>):Promise<RehydrationResult>{
 let snapshotResult:DomainResult<AuthoritativeIntelligenceSnapshot>;try{snapshotResult=await context.repository.readAuthoritativeSnapshot(request.environmentId,request.streamId,request.recordType,request.recordId)}catch{return quarantine(request.environmentId,request.recordId,context.now,'database_failure','$')}if(!snapshotResult.ok)return quarantine(request.environmentId,request.recordId,context.now,snapshotResult.error.code,snapshotResult.error.path);const authoritative=snapshotResult.value;if(request.expectedSnapshotId&&request.expectedSnapshotId!==authoritative.snapshotId)return quarantine(request.environmentId,request.recordId,context.now,'snapshot_bookmark_mismatch','$.snapshotId');const shape=validateSnapshotShape(authoritative,request.environmentId,request.recordId);if(!shape.ok)return quarantine(request.environmentId,request.recordId,context.now,shape.error.code,shape.error.path);
 let deletions:Readonly<Record<string,'active'|'deleted'>>;try{deletions=await context.deletionLedger.getDeletionStates(request.environmentId,authoritative.records.map(x=>x.record.recordId))}catch{return quarantine(request.environmentId,request.recordId,context.now,'database_failure','$.deletionLedger')}
 const keyCache=new Map<string,VerificationKey|undefined>(),cachedKeys:IntelligenceVerificationKeyProvider={async getVerificationKey(environmentId,keyId,at){const cacheId=`${environmentId}\0${keyId}\0${at}`;if(!keyCache.has(cacheId))keyCache.set(cacheId,await context.keys.getVerificationKey(environmentId,keyId,at));return keyCache.get(cacheId)}};
 let selected:AuthenticatedIntelligenceRecord|undefined,capability:NormalizedMarketSnapshot|undefined;for(const row of authoritative.records){const record=row.record;if(deletions[record.recordId]!=='active')return quarantine(request.environmentId,request.recordId,context.now,'deletion_required','$.records');const rights=validateRightsSchedule(row.rightsSchedule);if(!rights.ok||rights.value.scheduleId!==record.rightsScheduleId||!rights.value.permittedRecordTypes.includes(record.recordType))return quarantine(request.environmentId,request.recordId,context.now,'rights_expired','$.records');if(row.retention.status!=='retained'||(record.hardSourceDeleteAfter&&Date.parse(context.now)>=Date.parse(record.hardSourceDeleteAfter))||(record.projectDeleteAfter&&Date.parse(context.now)>=Date.parse(record.projectDeleteAfter)))return quarantine(request.environmentId,request.recordId,context.now,'deletion_required','$.records');if(row.keyMetadata.algorithm!=='HMAC-SHA-256'||row.keyMetadata.status==='revoked'||row.keyMetadata.status==='unavailable')return quarantine(request.environmentId,request.recordId,context.now,row.keyMetadata.status==='revoked'?'revoked_key':'parent_invalid','$.records');const verified=await verifyAuthenticatedRecord(record,request.environmentId,cachedKeys);if(!verified.ok)return quarantine(request.environmentId,request.recordId,context.now,record.recordId===request.recordId?verified.error.code:'parent_invalid','$.records');const resolvedKey=keyCache.get(`${request.environmentId}\0${record.keyId}\0${record.issuedAt}`);if(!resolvedKey||resolvedKey.algorithm!==row.keyMetadata.algorithm||resolvedKey.status!==row.keyMetadata.status||resolvedKey.activatesAt!==row.keyMetadata.activatesAt||(resolvedKey.verifyUntil??undefined)!==(row.keyMetadata.verifyUntil??undefined))return quarantine(request.environmentId,request.recordId,context.now,'parent_invalid','$.records');if(record.recordType!=='market_observation')return quarantine(request.environmentId,request.recordId,context.now,'unsupported_record_type','$.recordType');const domain=revalidatePersistedMarket(verified.value.payload);if(!domain.ok)return quarantine(request.environmentId,request.recordId,context.now,'domain_invalid','$.records');if(record.recordId===request.recordId){selected=verified.value;capability=domain.value}}
 if(!selected||!capability)return quarantine(request.environmentId,request.recordId,context.now,'parent_missing','$.records');const audit=deepFreeze({version:'intelligence-audit-event/1' as const,eventId:context.auditEventId,eventType:'record_rehydrated' as const,environmentId:request.environmentId,recordId:selected.recordId,occurredAt:context.now,metadata:{recordType:selected.recordType,rightsScheduleId:selected.rightsScheduleId,snapshotId:authoritative.snapshotId}});return ok(deepFreeze({record:selected,capability,audit,snapshotId:authoritative.snapshotId}));
}
