import { canonicalJsonText } from './canonical-json.ts';
import { deepFreeze, fail, ok, snapshot as contain, type DomainResult } from './domain-validation.ts';
import { normalizeMarketObservation, type NormalizedMarketSnapshot } from './market-observation.ts';
import { verifyAuthenticatedRecord, type AuthenticatedIntelligenceRecord, type IntelligenceVerificationKeyProvider, type VerificationKey } from './authenticated-record.ts';
import { validateRightsSchedule, type RightsSchedule } from './intelligence-rights.ts';
import type { AuthoritativeIntelligenceSnapshot, IntelligenceRecordRepository, SnapshotRecord } from './intelligence-repository.ts';

export type QuarantineReason='hash_mismatch'|'mac_mismatch'|'wrong_environment'|'unknown_key'|'revoked_key'|'key_period_invalid'|'rights_expired'|'deletion_required'|'parent_missing'|'parent_invalid'|'rollback_detected'|'unsupported_version'|'unsupported_record_type'|'domain_invalid'|'provider_or_port_failure'|'malformed_envelope';
export interface QuarantinePlan{readonly version:'intelligence-quarantine-plan/1';readonly environmentId:string;readonly recordId?:string;readonly reason:QuarantineReason;readonly createdAt:string;readonly metadata:Readonly<{failureCode:string;failurePath:string}>}
export interface AuditEvent{readonly version:'intelligence-audit-event/1';readonly eventId:string;readonly eventType:'record_rehydrated'|'record_quarantined'|'deletion_planned'|'restore_reconciled';readonly environmentId:string;readonly recordId?:string;readonly occurredAt:string;readonly metadata:Readonly<Record<string,string>>}
export interface ExternalDeletionLedger{getDeletionStates(environmentId:string,recordIds:readonly string[]):Promise<Readonly<Record<string,'active'|'deleted'>>>;recordContractualDeletion(input:Readonly<{environmentId:string;recordId:string;deletedAt:string;basis:string}>):Promise<void>}
export interface PostRestoreReconciliationPort{reconcileBeforeServing(input:Readonly<{environmentId:string;restoredAt:string;snapshotId:string}>):Promise<Readonly<{status:'safe'|'blocked';checkedRecords:number}>>}
export interface BackupExpiry{readonly backupRef:string;readonly expiresAt:string;readonly includesThrough:string}
export interface LegalHoldDecision{readonly version:'legal-hold-authorization/1';readonly authorityClass:'authorized_legal_hold';readonly authorityRef:string;readonly approverRef:string;readonly environmentId:string;readonly recordId:string;readonly scheduleId:string;readonly issuedAt:string;readonly expiresAt:string;readonly scope:'project_deletion_only';readonly status:'active'|'released'}
export interface LegalHoldAuthority{getDecision(environmentId:string,recordId:string,scheduleId:string,at:string):Promise<LegalHoldDecision|undefined>}
export interface DeletionPlan{readonly version:'intelligence-deletion-plan/1';readonly environmentId:string;readonly recordId:string;readonly action:'retain'|'delete';readonly executeAfter?:string;readonly basis:string;readonly legalHoldRef?:string}

function dataMember(input:unknown,key:string):DomainResult<unknown>{try{if(typeof input!=='object'||input===null||(Object.getPrototypeOf(input)!==Object.prototype&&Object.getPrototypeOf(input)!==null))return fail('provider_or_port_failure','Port boundary is invalid.','$');const descriptor=Object.getOwnPropertyDescriptor(input,key);return descriptor&&Object.hasOwn(descriptor,'value')?Object.freeze({ok:true as const,value:descriptor.value}):fail('provider_or_port_failure','Port boundary is invalid.','$')}catch{return fail('provider_or_port_failure','Port boundary is invalid.','$')}}
function containSnapshotResult(input:unknown):DomainResult<DomainResult<AuthoritativeIntelligenceSnapshot>>{try{const okMember=dataMember(input,'ok');if(!okMember.ok||typeof okMember.value!=='boolean')return fail('malformed_envelope','Repository result is invalid.','$');if(!okMember.value){const errorMember=dataMember(input,'error');if(!errorMember.ok)return fail('malformed_envelope','Repository result is invalid.','$');const safe=contain(errorMember.value);return safe.ok?ok({ok:false,error:safe.value as never}):fail('malformed_envelope','Repository result is invalid.','$')}const valueMember=dataMember(input,'value');if(!valueMember.ok)return fail('malformed_envelope','Repository result is invalid.','$');const source=valueMember.value,recordsMember=dataMember(source,'records');if(!recordsMember.ok||!Array.isArray(recordsMember.value)||recordsMember.value.length<1||recordsMember.value.length>17)return fail('malformed_envelope','Repository snapshot is invalid.','$');const records:SnapshotRecord[]=[];const seen=new WeakSet<object>();for(let index=0;index<recordsMember.value.length;index+=1){if(!Object.hasOwn(recordsMember.value,String(index)))return fail('malformed_envelope','Repository snapshot is invalid.','$');const row=recordsMember.value[index];if(typeof row!=='object'||row===null||seen.has(row))return fail('malformed_envelope','Repository snapshot is invalid.','$');seen.add(row);for(const key of['record','rightsSchedule','retention','keyMetadata','parents']){const member=dataMember(row,key);if(!member.ok)return fail('malformed_envelope','Repository snapshot is invalid.','$');if(typeof member.value==='object'&&member.value!==null){if(seen.has(member.value))return fail('malformed_envelope','Repository snapshot contains aliases.','$');seen.add(member.value)}}const safe=contain(row);if(!safe.ok)return fail('malformed_envelope','Repository snapshot is invalid.','$');records.push(safe.value as unknown as SnapshotRecord)}const header:Record<string,unknown>={records};for(const key of['version','snapshotId','environmentId','streamId','recordType','selectedRecordId','currentHeadId','headRevision']){const member=dataMember(source,key);if(!member.ok||(!['string','number'].includes(typeof member.value)))return fail('malformed_envelope','Repository snapshot is invalid.','$');header[key]=member.value}return ok({ok:true,value:header as unknown as AuthoritativeIntelligenceSnapshot})}catch{return fail('malformed_envelope','Repository result could not be inspected.','$')}}

export async function planDeletion(record:AuthenticatedIntelligenceRecord,schedule:RightsSchedule,status:string,now:string,holds:LegalHoldAuthority):Promise<DomainResult<DeletionPlan>>{
 const inputs=contain({record,schedule,status,now});if(!inputs.ok)return fail('invalid_input','Deletion request failed bounded inspection.',inputs.error.path);const clean=inputs.value as unknown as {record:AuthenticatedIntelligenceRecord;schedule:RightsSchedule;status:string;now:string};record=clean.record;schedule=clean.schedule;status=clean.status;now=clean.now;const get=dataMember(holds,'getDecision');if(!get.ok||typeof get.value!=='function')return fail('provider_or_port_failure','Legal-hold authority failed.','$');let hold:LegalHoldDecision|undefined;try{const raw=await (get.value as LegalHoldAuthority['getDecision']).call(holds,record.environmentId,record.recordId,schedule.scheduleId,now);if(raw!==undefined){const safe=contain(raw);if(!safe.ok)return fail('provider_or_port_failure','Legal-hold authority returned invalid data.','$');hold=safe.value as unknown as LegalHoldDecision}}catch{return fail('provider_or_port_failure','Legal-hold authority failed.','$')};const hard=record.hardSourceDeleteAfter,project=record.projectDeleteAfter,hardDue=!!hard&&Date.parse(now)>=Date.parse(hard),forced=status==='delete_required'||status==='deleted'||status==='provider_exit'||hardDue;
 const valid=!!hold&&schedule.legalHoldHandling==='honour_valid_hold'&&hold.version==='legal-hold-authorization/1'&&hold.authorityClass==='authorized_legal_hold'&&hold.environmentId===record.environmentId&&hold.recordId===record.recordId&&hold.scheduleId===schedule.scheduleId&&hold.scope==='project_deletion_only'&&hold.status==='active'&&Date.parse(hold.issuedAt)<=Date.parse(now)&&Date.parse(now)<Date.parse(hold.expiresAt);
 if(forced)return ok(deepFreeze({version:'intelligence-deletion-plan/1',environmentId:record.environmentId,recordId:record.recordId,action:'delete',...(hard?{executeAfter:hard}:{}),basis:status==='provider_exit'?'provider_exit':'hard_source_rights_or_required_deletion'}));if(valid&&hold&&project&&Date.parse(now)>=Date.parse(project))return ok(deepFreeze({version:'intelligence-deletion-plan/1',environmentId:record.environmentId,recordId:record.recordId,action:'retain',basis:'authorized_project_deletion_pause',legalHoldRef:hold.authorityRef}));const due=!!project&&Date.parse(now)>=Date.parse(project);return ok(deepFreeze({version:'intelligence-deletion-plan/1',environmentId:record.environmentId,recordId:record.recordId,action:due?'delete':'retain',...(project?{executeAfter:project}:{}),basis:due?'project_retention_expired':'within_source_and_project_rights'}));
}

export type RehydratedIntelligence=Readonly<{record:AuthenticatedIntelligenceRecord;capability:NormalizedMarketSnapshot;audit:AuditEvent;snapshotId:string}>;
export type RehydrationResult=DomainResult<RehydratedIntelligence>|Readonly<{ok:false;error:Readonly<{code:'quarantine_required';message:string;path:string;metadata:Readonly<{plan:QuarantinePlan}>}>}>;
export type QuarantineFailureCode='hash_mismatch'|'mac_mismatch'|'wrong_environment'|'unknown_key'|'revoked_key'|'key_period_invalid'|'rights_expired'|'deletion_required'|'parent_missing'|'parent_invalid'|'rollback_detected'|'snapshot_not_found'|'snapshot_bookmark_mismatch'|'unsupported_version'|'unsupported_record_type'|'domain_invalid'|'provider_or_port_failure'|'database_failure'|'key_provider_failure'|'cryptographic_failure'|'malformed_envelope'|'invalid_input'|'unknown_field'|'credential_field'|'inspection_limit_exceeded'|'repeated_reference'|'snapshot_limit_exceeded'|'invalid_rights_schedule'|'contradictory_rights'|'source_not_permitted'|'invalid_retention'|'key_policy_mismatch';
const MAP=Object.freeze({hash_mismatch:'hash_mismatch',mac_mismatch:'mac_mismatch',wrong_environment:'wrong_environment',unknown_key:'unknown_key',revoked_key:'revoked_key',key_period_invalid:'key_period_invalid',rights_expired:'rights_expired',deletion_required:'deletion_required',parent_missing:'parent_missing',parent_invalid:'parent_invalid',rollback_detected:'rollback_detected',snapshot_not_found:'rollback_detected',snapshot_bookmark_mismatch:'rollback_detected',unsupported_version:'unsupported_version',unsupported_record_type:'unsupported_record_type',domain_invalid:'domain_invalid',provider_or_port_failure:'provider_or_port_failure',database_failure:'provider_or_port_failure',key_provider_failure:'provider_or_port_failure',cryptographic_failure:'provider_or_port_failure',malformed_envelope:'malformed_envelope',invalid_input:'malformed_envelope',unknown_field:'malformed_envelope',credential_field:'malformed_envelope',inspection_limit_exceeded:'malformed_envelope',repeated_reference:'malformed_envelope',snapshot_limit_exceeded:'parent_invalid',invalid_rights_schedule:'rights_expired',contradictory_rights:'rights_expired',source_not_permitted:'rights_expired',invalid_retention:'rights_expired',key_policy_mismatch:'key_period_invalid'} satisfies Readonly<Record<QuarantineFailureCode,QuarantineReason>>);
export function quarantineReasonForFailure(code:QuarantineFailureCode):QuarantineReason{return MAP[code]}
function classify(code:string):QuarantineFailureCode{return Object.hasOwn(MAP,code)?code as QuarantineFailureCode:'malformed_envelope'}
function quarantine(environmentId:string,recordId:string|undefined,now:string,rawCode:string,path:string):RehydrationResult{const code=classify(rawCode),reason=quarantineReasonForFailure(code),plan=deepFreeze({version:'intelligence-quarantine-plan/1' as const,environmentId,...(recordId?{recordId}:{}),reason,createdAt:now,metadata:{failureCode:code.slice(0,64),failurePath:path.slice(0,128)}});try{canonicalJsonText(plan,2048)}catch{return{ok:false,error:deepFreeze({code:'quarantine_required' as const,message:'Record requires quarantine; history is not repaired.',path:'$',metadata:{plan:{...plan,metadata:{failureCode:'malformed_envelope',failurePath:'$'}}}})}}return{ok:false,error:deepFreeze({code:'quarantine_required' as const,message:'Record requires quarantine; history is not repaired.',path,metadata:{plan}})}}

function validateSnapshotShape(snapshot:AuthoritativeIntelligenceSnapshot,environmentId:string,recordId:string):DomainResult<true>{if(snapshot.environmentId!==environmentId||snapshot.selectedRecordId!==recordId)return fail('snapshot_bookmark_mismatch','Snapshot identity does not match request.','$');if(snapshot.currentHeadId!==recordId)return fail('rollback_detected','Selected record is not current.','$.currentHeadId');if(snapshot.records.length<1||snapshot.records.length>17)return fail('parent_invalid','Snapshot row count is invalid.','$.records');const ids=new Set<string>();for(const row of snapshot.records){const r=row.record;if(ids.has(r.recordId))return fail('parent_invalid','Cycle or duplicate ancestry detected.','$.records');ids.add(r.recordId);if(r.environmentId!==environmentId||r.streamId!==snapshot.streamId||r.recordType!==snapshot.recordType||row.parents.length!==r.parentRefs.length||row.parents.some((p,i)=>p!==r.parentRefs[i]))return fail('parent_invalid','Ancestry scope or edges are inconsistent.','$.records')}for(const row of snapshot.records)for(const parent of row.parents)if(!ids.has(parent))return fail('parent_missing','Required ancestor is absent.','$.records');return ok(true)}
function revalidatePersistedMarket(payload:unknown){if(typeof payload!=='object'||payload===null||Array.isArray(payload))return normalizeMarketObservation(payload);const value=payload as Record<string,unknown>;if(value.contractVersion!=='market-observation-v1'||!Array.isArray(value.outcomes))return normalizeMarketObservation(payload);return normalizeMarketObservation({sourceEnvelope:value.sourceEnvelope,sportId:value.sportId,competitionId:value.competitionId,eventId:value.eventId,marketId:value.marketId,eventStartAt:value.eventStartAt,asOf:value.asOf,freshnessPolicy:value.freshnessPolicy,completeness:value.completeness,marketAvailability:value.marketAvailability,outcomes:value.outcomes.map(item=>{const outcome=item as Record<string,unknown>;return{outcomeId:outcome.outcomeId,...(outcome.decimalOdds!==undefined?{decimalOdds:outcome.decimalOdds}:{}),availability:outcome.availability,observationRef:outcome.observationRef,...(outcome.sourceSequence!==undefined?{sourceSequence:outcome.sourceSequence}:{}),identity:{sportId:value.sportId,competitionId:value.competitionId,eventId:value.eventId,marketId:value.marketId,outcomeId:outcome.outcomeId}}})})}

export async function rehydrateIntelligenceRecord(request:Readonly<{environmentId:string;streamId:string;recordType:string;recordId:string;expectedSnapshotId?:string}>,context:Readonly<{now:string;keys:IntelligenceVerificationKeyProvider;repository:IntelligenceRecordRepository;deletionLedger:ExternalDeletionLedger;auditEventId:string}>):Promise<RehydrationResult>{
 const requestSafe=contain(request);if(!requestSafe.ok)return quarantine('unknown',undefined,new Date(0).toISOString(),'malformed_envelope','$');request=requestSafe.value as unknown as typeof request;const nowValue=dataMember(context,'now'),auditValue=dataMember(context,'auditEventId'),keysValue=dataMember(context,'keys'),repositoryValue=dataMember(context,'repository'),ledgerValue=dataMember(context,'deletionLedger');if(!nowValue.ok||!auditValue.ok||!keysValue.ok||!repositoryValue.ok||!ledgerValue.ok||typeof nowValue.value!=='string'||typeof auditValue.value!=='string')return quarantine(request.environmentId,request.recordId,new Date(0).toISOString(),'provider_or_port_failure','$');const now=nowValue.value,auditEventId=auditValue.value,repository=repositoryValue.value as IntelligenceRecordRepository,ledger=ledgerValue.value as ExternalDeletionLedger,keys=keysValue.value as IntelligenceVerificationKeyProvider;const read=dataMember(repository,'readAuthoritativeSnapshot');if(!read.ok||typeof read.value!=='function')return quarantine(request.environmentId,request.recordId,now,'provider_or_port_failure','$');
 let snapshotResult:DomainResult<AuthoritativeIntelligenceSnapshot>;try{const raw=await (read.value as IntelligenceRecordRepository['readAuthoritativeSnapshot']).call(repository,request.environmentId,request.streamId,request.recordType,request.recordId),safe=containSnapshotResult(raw);if(!safe.ok)return quarantine(request.environmentId,request.recordId,now,'malformed_envelope','$');snapshotResult=safe.value}catch{return quarantine(request.environmentId,request.recordId,now,'database_failure','$')}if(!snapshotResult.ok)return quarantine(request.environmentId,request.recordId,now,snapshotResult.error.code,snapshotResult.error.path);const authoritative=snapshotResult.value;if(request.expectedSnapshotId&&request.expectedSnapshotId!==authoritative.snapshotId)return quarantine(request.environmentId,request.recordId,now,'snapshot_bookmark_mismatch','$.snapshotId');const shape=validateSnapshotShape(authoritative,request.environmentId,request.recordId);if(!shape.ok)return quarantine(request.environmentId,request.recordId,now,shape.error.code,shape.error.path);
 const getDeletion=dataMember(ledger,'getDeletionStates');if(!getDeletion.ok||typeof getDeletion.value!=='function')return quarantine(request.environmentId,request.recordId,now,'provider_or_port_failure','$.deletionLedger');let deletions:Readonly<Record<string,'active'|'deleted'>>;try{const raw=await (getDeletion.value as ExternalDeletionLedger['getDeletionStates']).call(ledger,request.environmentId,authoritative.records.map(x=>x.record.recordId)),safe=contain(raw);if(!safe.ok)return quarantine(request.environmentId,request.recordId,now,'provider_or_port_failure','$.deletionLedger');deletions=safe.value as unknown as typeof deletions}catch{return quarantine(request.environmentId,request.recordId,now,'provider_or_port_failure','$.deletionLedger')}
 const getKey=dataMember(keys,'getVerificationKey');if(!getKey.ok||typeof getKey.value!=='function')return quarantine(request.environmentId,request.recordId,now,'provider_or_port_failure','$.keys');const keyCache=new Map<string,VerificationKey|undefined>(),cachedKeys:IntelligenceVerificationKeyProvider={async getVerificationKey(environmentId,keyId,at){const cacheId=`${environmentId}\0${keyId}\0${at}`;if(!keyCache.has(cacheId))keyCache.set(cacheId,await (getKey.value as IntelligenceVerificationKeyProvider['getVerificationKey']).call(keys,environmentId,keyId,at));return keyCache.get(cacheId)}};
 let selected:AuthenticatedIntelligenceRecord|undefined,capability:NormalizedMarketSnapshot|undefined;for(const row of authoritative.records){const record=row.record;if(deletions[record.recordId]!=='active')return quarantine(request.environmentId,request.recordId,now,'deletion_required','$.records');const rights=validateRightsSchedule(row.rightsSchedule);if(!rights.ok||rights.value.scheduleId!==record.rightsScheduleId||!rights.value.permittedRecordTypes.includes(record.recordType))return quarantine(request.environmentId,request.recordId,now,'rights_expired','$.records');if(row.retention.status!=='retained'||(record.hardSourceDeleteAfter&&Date.parse(now)>=Date.parse(record.hardSourceDeleteAfter))||(record.projectDeleteAfter&&Date.parse(now)>=Date.parse(record.projectDeleteAfter)))return quarantine(request.environmentId,request.recordId,now,'deletion_required','$.records');if(row.keyMetadata.algorithm!=='HMAC-SHA-256'||row.keyMetadata.status==='revoked'||row.keyMetadata.status==='unavailable')return quarantine(request.environmentId,request.recordId,now,row.keyMetadata.status==='revoked'?'revoked_key':'parent_invalid','$.records');const verified=await verifyAuthenticatedRecord(record,request.environmentId,cachedKeys);if(!verified.ok)return quarantine(request.environmentId,request.recordId,now,record.recordId===request.recordId?verified.error.code:'parent_invalid','$.records');const resolvedKey=keyCache.get(`${request.environmentId}\0${record.keyId}\0${record.issuedAt}`);if(!resolvedKey||resolvedKey.algorithm!==row.keyMetadata.algorithm||resolvedKey.status!==row.keyMetadata.status||resolvedKey.activatesAt!==row.keyMetadata.activatesAt||(resolvedKey.verifyUntil??undefined)!==(row.keyMetadata.verifyUntil??undefined))return quarantine(request.environmentId,request.recordId,now,'parent_invalid','$.records');if(record.recordType!=='market_observation')return quarantine(request.environmentId,request.recordId,now,'unsupported_record_type','$.recordType');const domain=revalidatePersistedMarket(verified.value.payload);if(!domain.ok)return quarantine(request.environmentId,request.recordId,now,'domain_invalid','$.records');if(record.recordId===request.recordId){selected=verified.value;capability=domain.value}}
 if(!selected||!capability)return quarantine(request.environmentId,request.recordId,now,'parent_missing','$.records');const audit=deepFreeze({version:'intelligence-audit-event/1' as const,eventId:auditEventId,eventType:'record_rehydrated' as const,environmentId:request.environmentId,recordId:selected.recordId,occurredAt:now,metadata:{recordType:selected.recordType,rightsScheduleId:selected.rightsScheduleId,snapshotId:authoritative.snapshotId}});return ok(deepFreeze({record:selected,capability,audit,snapshotId:authoritative.snapshotId}));
}
