import { canonicalJsonText } from './canonical-json.ts';
import { deepFreeze, fail, ok, snapshot, timestamp, type DomainResult } from './domain-validation.ts';
import { RECORD_LIMITS, type AuthenticatedIntelligenceRecord } from './authenticated-record.ts';

export interface D1PreparedStatementLike{bind(...values:unknown[]):D1PreparedStatementLike;first<T=Record<string,unknown>>():Promise<T|null>;all<T=Record<string,unknown>>():Promise<{results:T[]}>}
export interface D1ResultLike{readonly success:boolean;readonly meta?:Readonly<{changes?:number}>}
export interface D1DatabaseLike{prepare(query:string):D1PreparedStatementLike;batch(statements:D1PreparedStatementLike[]):Promise<D1ResultLike[]>}
export interface AppendRequest{readonly record:AuthenticatedIntelligenceRecord;readonly idempotencyKey:string;readonly auditEventId:string;readonly appendedAt:string}
export interface AppendResult{readonly status:'appended'|'idempotent';readonly recordId:string;readonly streamId:string}
export interface RotateKeyRequest{readonly environmentId:string;readonly rotationId:string;readonly expected:Readonly<{keyId:string;algorithm:'HMAC-SHA-256';activatesAt:string;identityMetadata:unknown}>;readonly expectedStatusEventId:string;readonly demotionEventId:string;readonly replacement:Readonly<{keyId:string;algorithm:'HMAC-SHA-256';activatesAt:string;identityMetadata:unknown}>;readonly replacementActivationEventId:string;readonly auditEventId:string;readonly occurredAt:string;readonly reasonRef:string;readonly issuerRef:string}
export interface RotateKeyResult{readonly status:'rotated'|'idempotent';readonly rotationId:string;readonly previousKeyId:string;readonly activeKeyId:string}
export interface SnapshotRecord{readonly record:AuthenticatedIntelligenceRecord;readonly rightsSchedule:unknown;readonly retention:Readonly<{status:string;projectDeleteAfter?:string;hardSourceDeleteAfter?:string}>;readonly keyMetadata:Readonly<{algorithm:string;status:string;activatesAt:string;statusEffectiveAt:string;verifyUntil?:string}>;readonly parents:readonly string[]}
export interface AuthoritativeIntelligenceSnapshot{readonly version:'authoritative-intelligence-snapshot/1';readonly snapshotId:string;readonly environmentId:string;readonly streamId:string;readonly recordType:string;readonly selectedRecordId:string;readonly currentHeadId:string;readonly headRevision:number;readonly records:readonly SnapshotRecord[]}
export interface IntelligenceRecordRepository{append(request:AppendRequest):Promise<DomainResult<AppendResult>>;rotateKey(request:RotateKeyRequest):Promise<DomainResult<RotateKeyResult>>;readAuthoritativeSnapshot(environmentId:string,streamId:string,recordType:string,recordId:string):Promise<DomainResult<AuthoritativeIntelligenceSnapshot>>}
const IDEMPOTENCY=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/,MAX_ROWS=17;
type Existing={record_id:string;stream_id:string;record_type:string;rights_schedule_id:string;key_id:string;content_hash:string;authentication_tag:string;header_jcs:string;payload_jcs:string;parent_head_id:string|null};

const SNAPSHOT_SQL=`WITH RECURSIVE ancestry(record_id,depth) AS (
 SELECT ?1,0 UNION SELECT p.parent_record_id,a.depth+1 FROM ancestry a JOIN intelligence_record_parents p ON p.environment_id=?2 AND p.child_record_id=a.record_id WHERE a.depth<16
), bounded AS (SELECT record_id,depth FROM ancestry ORDER BY depth LIMIT 17)
SELECT r.*,h.current_record_id,h.revision,rs.schedule_jcs,k.algorithm key_algorithm,ks.status key_status,k.activates_at key_activates_at,ks.status_effective_at key_status_effective_at,NULL key_verify_until,
(SELECT re.status FROM intelligence_retention_events re WHERE re.environment_id=r.environment_id AND re.record_id=r.record_id ORDER BY re.occurred_at DESC,re.event_id DESC LIMIT 1) retention_status,
(SELECT re.project_delete_after FROM intelligence_retention_events re WHERE re.environment_id=r.environment_id AND re.record_id=r.record_id ORDER BY re.occurred_at DESC,re.event_id DESC LIMIT 1) retention_project_delete_after,
(SELECT re.hard_source_delete_after FROM intelligence_retention_events re WHERE re.environment_id=r.environment_id AND re.record_id=r.record_id ORDER BY re.occurred_at DESC,re.event_id DESC LIMIT 1) retention_hard_source_delete_after,
p.parent_record_id parent_id,b.depth
FROM bounded b JOIN authenticated_intelligence_records r ON r.environment_id=?2 AND r.record_id=b.record_id JOIN intelligence_record_commits c ON c.environment_id=r.environment_id AND c.record_id=r.record_id
JOIN intelligence_finalization_receipts f ON f.environment_id=c.environment_id AND f.record_id=c.record_id
JOIN intelligence_stream_heads h ON h.environment_id=r.environment_id AND h.stream_id=?3 AND h.record_type=?4 JOIN intelligence_rights_schedules rs ON rs.environment_id=r.environment_id AND rs.schedule_id=r.rights_schedule_id
JOIN intelligence_keys k ON k.environment_id=r.environment_id AND k.key_id=r.key_id JOIN intelligence_current_key_status ks ON ks.environment_id=k.environment_id AND ks.key_id=k.key_id
LEFT JOIN intelligence_record_parents p ON p.environment_id=r.environment_id AND p.child_record_id=r.record_id WHERE r.stream_id=?3 AND r.record_type=?4 ORDER BY b.depth LIMIT 17`;

function safeRow(input:unknown):DomainResult<Record<string,unknown>>{try{if(typeof input!=='object'||input===null||Array.isArray(input)||(Object.getPrototypeOf(input)!==Object.prototype&&Object.getPrototypeOf(input)!==null)||Reflect.ownKeys(input).some(k=>typeof k!=='string')||Reflect.ownKeys(input).length>48)return fail('malformed_envelope','Database row is malformed.','$');const out:Record<string,unknown>=Object.create(null);for(const key of Reflect.ownKeys(input)as string[]){const d=Object.getOwnPropertyDescriptor(input,key);if(!d||!Object.hasOwn(d,'value'))return fail('malformed_envelope','Database row is malformed.','$');if(typeof d.value==='string'&&d.value.length>(key==='payload_jcs'?RECORD_LIMITS.maxPayloadBytes:8192))return fail('malformed_envelope','Database row exceeds bounds.','$');if(d.value!==null&&!['string','number','boolean'].includes(typeof d.value))return fail('malformed_envelope','Database row is malformed.','$');out[key]=d.value}return ok(out)}catch{return fail('malformed_envelope','Database row could not be inspected.','$')}}
function safeResults(input:unknown):DomainResult<unknown[]>{try{if(typeof input!=='object'||input===null)return fail('database_failure','Authoritative snapshot result is malformed.','$');const d=Object.getOwnPropertyDescriptor(input,'results');if(!d||!Object.hasOwn(d,'value')||!Array.isArray(d.value))return fail('database_failure','Authoritative snapshot result is malformed.','$');const length=Object.getOwnPropertyDescriptor(d.value,'length');if(!length||!Object.hasOwn(length,'value')||!Number.isSafeInteger(length.value)||length.value>MAX_ROWS)return fail('database_failure','Authoritative snapshot result is malformed.','$');const out:unknown[]=[];for(let i=0;i<length.value;i+=1){const entry=Object.getOwnPropertyDescriptor(d.value,String(i));if(!entry||!Object.hasOwn(entry,'value'))return fail('database_failure','Authoritative snapshot result is malformed.','$');out.push(entry.value)}return ok(out)}catch{return fail('database_failure','Authoritative snapshot result is malformed.','$')}}
function parsed(text:unknown,path:string):DomainResult<unknown>{if(typeof text!=='string')return fail('malformed_envelope','Stored JSON is malformed.',path);try{const value=JSON.parse(text)as unknown,safe=snapshot(value);return safe.ok?ok(safe.value):fail('malformed_envelope','Stored JSON is malformed.',path)}catch{return fail('malformed_envelope','Stored JSON is malformed.',path)}}
function same(existing:Existing,r:AuthenticatedIntelligenceRecord,headerJcs:string,payloadJcs:string,idempotencyKey:string){return existing.record_id===r.recordId&&existing.stream_id===r.streamId&&existing.record_type===r.recordType&&existing.rights_schedule_id===r.rightsScheduleId&&existing.key_id===r.keyId&&existing.content_hash===r.contentHash&&existing.authentication_tag===r.authenticationTag&&existing.header_jcs===headerJcs&&existing.payload_jcs===payloadJcs&&(existing.parent_head_id??undefined)===(r.parentRefs[0]??undefined)&&IDEMPOTENCY.test(idempotencyKey)}
type ExistingRotation={rotation_id:string;expected_key_id:string;expected_algorithm:string;expected_activates_at:string;expected_identity_jcs:string;expected_status_event_id:string;demotion_event_id:string;replacement_key_id:string;replacement_activation_event_id:string;replacement_algorithm:string;replacement_activates_at:string;replacement_identity_jcs:string;reason_ref:string;issuer_ref:string;audit_event_id:string;occurred_at:string};
function sameRotation(row:ExistingRotation,r:RotateKeyRequest,expectedIdentityJcs:string,replacementIdentityJcs:string){return row.rotation_id===r.rotationId&&row.expected_key_id===r.expected.keyId&&row.expected_algorithm===r.expected.algorithm&&row.expected_activates_at===r.expected.activatesAt&&row.expected_identity_jcs===expectedIdentityJcs&&row.expected_status_event_id===r.expectedStatusEventId&&row.demotion_event_id===r.demotionEventId&&row.replacement_key_id===r.replacement.keyId&&row.replacement_activation_event_id===r.replacementActivationEventId&&row.replacement_algorithm===r.replacement.algorithm&&row.replacement_activates_at===r.replacement.activatesAt&&row.replacement_identity_jcs===replacementIdentityJcs&&row.reason_ref===r.reasonRef&&row.issuer_ref===r.issuerRef&&row.audit_event_id===r.auditEventId&&row.occurred_at===r.occurredAt}
function exactMutationResults(input:unknown,expected:number):DomainResult<true>{const safe=snapshot(input);if(!safe.ok)return fail('database_result_invalid','Database mutation metadata is invalid.','$');if(!Array.isArray(safe.value)||safe.value.length!==expected)return fail('database_result_invalid','Database mutation metadata is invalid.','$');for(const item of safe.value){if(typeof item!=='object'||item===null||Array.isArray(item)||item.success!==true||typeof item.meta!=='object'||item.meta===null||Array.isArray(item.meta)||!Number.isSafeInteger(item.meta.changes)||item.meta.changes!==1)return fail('database_result_invalid','Database mutation metadata is invalid.','$')}return ok(true)}

export class D1IntelligenceRecordRepository implements IntelligenceRecordRepository{
 private readonly db:D1DatabaseLike;constructor(db:D1DatabaseLike){this.db=db}
 private async existing(environmentId:string,idempotencyKey:string):Promise<DomainResult<Existing|null>>{try{const raw=await this.db.prepare('SELECT record_id,stream_id,record_type,rights_schedule_id,key_id,content_hash,authentication_tag,header_jcs,payload_jcs,parent_head_id FROM authenticated_intelligence_records WHERE environment_id=? AND idempotency_key=?').bind(environmentId,idempotencyKey).first<Existing>();if(raw===null)return ok(null);const safe=safeRow(raw);return safe.ok?ok(safe.value as unknown as Existing):safe}catch{return fail('database_failure','Database read failed.','$.idempotencyKey')}}
 async append(input:AppendRequest):Promise<DomainResult<AppendResult>>{
  const safe=snapshot(input);if(!safe.ok)return fail('invalid_input','Append request failed bounded inspection.',safe.error.path);const request=safe.value as unknown as AppendRequest;if(!IDEMPOTENCY.test(request.idempotencyKey))return fail('invalid_idempotency_key','Idempotency key is invalid.','$.idempotencyKey');const r=request.record;if(r.parentRefs.length>1)return fail('parent_invalid','Only one linear parent is supported.','$.record.parentRefs');
  let payloadJcs:string,headerJcs:string;try{payloadJcs=canonicalJsonText(r.payload,RECORD_LIMITS.maxPayloadBytes);headerJcs=canonicalJsonText(Object.fromEntries(Object.entries(r).filter(([k])=>!['payload','contentHash','authenticationTag'].includes(k))))}catch{return fail('invalid_input','Record serialization failed.','$.record')}
  const before=await this.existing(r.environmentId,request.idempotencyKey);if(!before.ok)return before;if(before.value)return same(before.value,r,headerJcs,payloadJcs,request.idempotencyKey)?ok(deepFreeze({status:'idempotent',recordId:r.recordId,streamId:r.streamId})):fail('idempotency_collision','Idempotency key has different content.','$.idempotencyKey');
  const parent=r.parentRefs[0]??null,transition=`${request.auditEventId}:transition`,receipt=`${request.auditEventId}:receipt`;
  const statements=[
   this.db.prepare('INSERT INTO authenticated_intelligence_records(environment_id,record_id,stream_id,record_type,schema_version,contract_version,rights_schedule_id,key_id,idempotency_key,content_hash,authentication_tag,header_jcs,payload_jcs,declared_parent_count,parent_head_id,corrects_record_id,issued_at,validated_at,project_delete_after,hard_source_delete_after,indefinite_basis) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(r.environmentId,r.recordId,r.streamId,r.recordType,r.schemaVersion,r.contractVersion,r.rightsScheduleId,r.keyId,request.idempotencyKey,r.contentHash,r.authenticationTag,headerJcs,payloadJcs,r.parentRefs.length,parent,r.correctsRecordId??null,r.issuedAt,r.validatedAt,r.projectDeleteAfter??null,r.hardSourceDeleteAfter??null,r.indefiniteBasis??null),
   ...(parent?[this.db.prepare('INSERT INTO intelligence_record_parents(environment_id,child_record_id,child_stream_id,child_record_type,parent_record_id,parent_stream_id,parent_record_type,ordinal) VALUES(?,?,?,?,?,?,?,0)').bind(r.environmentId,r.recordId,r.streamId,r.recordType,parent,r.streamId,r.recordType)]:[]),
   this.db.prepare('INSERT INTO intelligence_head_transitions(environment_id,transition_id,stream_id,record_type,expected_head_id,new_record_id,expected_revision,new_revision,created_at) SELECT ?,?,?,?,?,?,COALESCE(h.revision,0),COALESCE(h.revision,0)+1,? FROM (SELECT 1) seed LEFT JOIN intelligence_stream_heads h ON h.environment_id=? AND h.stream_id=? AND h.record_type=? WHERE (? IS NULL AND h.current_record_id IS NULL) OR (? IS NOT NULL AND h.current_record_id=?)').bind(r.environmentId,transition,r.streamId,r.recordType,parent,r.recordId,request.appendedAt,r.environmentId,r.streamId,r.recordType,parent,parent,parent),
   this.db.prepare('INSERT INTO intelligence_record_commits(environment_id,record_id,transition_id,committed_at,commit_version) VALUES(?,?,?,?,?)').bind(r.environmentId,r.recordId,transition,request.appendedAt,'intelligence-record-commit/2'),
   parent===null?this.db.prepare('INSERT INTO intelligence_stream_heads(environment_id,stream_id,record_type,current_record_id,revision) SELECT environment_id,stream_id,record_type,new_record_id,new_revision FROM intelligence_head_transitions WHERE environment_id=? AND transition_id=?').bind(r.environmentId,transition):this.db.prepare('UPDATE intelligence_stream_heads SET current_record_id=?,revision=revision+1 WHERE environment_id=? AND stream_id=? AND record_type=? AND current_record_id=? AND revision=(SELECT expected_revision FROM intelligence_head_transitions WHERE environment_id=? AND transition_id=?)').bind(r.recordId,r.environmentId,r.streamId,r.recordType,parent,r.environmentId,transition),
   this.db.prepare('INSERT INTO intelligence_finalization_receipts(environment_id,receipt_id,transition_id,record_id,stream_id,record_type,revision,created_at) SELECT environment_id,?,transition_id,new_record_id,stream_id,record_type,new_revision,? FROM intelligence_head_transitions WHERE environment_id=? AND transition_id=?').bind(receipt,request.appendedAt,r.environmentId,transition),
   this.db.prepare('INSERT INTO intelligence_retention_events(environment_id,event_id,record_id,status,project_delete_after,hard_source_delete_after,occurred_at,metadata_jcs) VALUES(?,?,?,?,?,?,?,?)').bind(r.environmentId,`${request.auditEventId}:retention`,r.recordId,'retained',r.projectDeleteAfter??null,r.hardSourceDeleteAfter??null,request.appendedAt,'{}'),
   this.db.prepare('INSERT INTO intelligence_audit_events(environment_id,event_id,event_type,record_id,occurred_at,metadata_jcs) VALUES(?,?,?,?,?,?)').bind(r.environmentId,request.auditEventId,'record_appended',r.recordId,request.appendedAt,canonicalJsonText({streamId:r.streamId,recordType:r.recordType}))];
  try{const meta=snapshot(await this.db.batch(statements));if(!meta.ok||!Array.isArray(meta.value)||meta.value.length!==statements.length||meta.value.some(x=>typeof x!=='object'||x===null||Array.isArray(x)||x.success!==true))return fail('database_failure','Atomic database append failed.','$.record');return ok(deepFreeze({status:'appended',recordId:r.recordId,streamId:r.streamId}))}catch{const after=await this.existing(r.environmentId,request.idempotencyKey);if(after.ok&&after.value)return same(after.value,r,headerJcs,payloadJcs,request.idempotencyKey)?ok(deepFreeze({status:'idempotent',recordId:r.recordId,streamId:r.streamId})):fail('idempotency_collision','Idempotency key has different content.','$.idempotencyKey');return fail('head_conflict','Atomic append was rejected.','$.record.parentRefs')}
 }
 async rotateKey(input:RotateKeyRequest):Promise<DomainResult<RotateKeyResult>>{
  const safe=snapshot(input);if(!safe.ok)return fail('invalid_input','Rotation request failed bounded inspection.',safe.error.path);const request=safe.value as unknown as RotateKeyRequest,ids=[request.environmentId,request.rotationId,request.expected.keyId,request.expectedStatusEventId,request.demotionEventId,request.replacement.keyId,request.replacementActivationEventId,request.auditEventId,request.reasonRef,request.issuerRef];if(ids.some(id=>typeof id!=='string'||!IDEMPOTENCY.test(id))||request.expected.keyId===request.replacement.keyId||request.expected.algorithm!=='HMAC-SHA-256'||request.replacement.algorithm!=='HMAC-SHA-256')return fail('invalid_key_rotation','Rotation identifiers or key identity are invalid.','$');for(const[field,value]of[['occurredAt',request.occurredAt],['expected.activatesAt',request.expected.activatesAt],['replacement.activatesAt',request.replacement.activatesAt]]as const){const parsed=timestamp(value,`$.${field}`);if(!parsed.ok)return fail('invalid_key_rotation','Rotation timestamp is invalid.',parsed.error.path)}if(Date.parse(request.replacement.activatesAt)>Date.parse(request.occurredAt))return fail('invalid_key_rotation','Replacement activation cannot follow rotation.','$.replacement.activatesAt');let expectedIdentityJcs:string,replacementIdentityJcs:string;try{expectedIdentityJcs=canonicalJsonText(request.expected.identityMetadata,2048);replacementIdentityJcs=canonicalJsonText(request.replacement.identityMetadata,2048)}catch{return fail('invalid_key_rotation','Key identity metadata is invalid.','$')}
  const read=async():Promise<DomainResult<ExistingRotation|null>>=>{try{const raw=await this.db.prepare('SELECT rotation_id,expected_key_id,expected_algorithm,expected_activates_at,expected_identity_jcs,expected_status_event_id,demotion_event_id,replacement_key_id,replacement_activation_event_id,replacement_algorithm,replacement_activates_at,replacement_identity_jcs,reason_ref,issuer_ref,audit_event_id,occurred_at FROM intelligence_key_rotations WHERE environment_id=? AND rotation_id=?').bind(request.environmentId,request.rotationId).first<ExistingRotation>();if(raw===null)return ok(null);const contained=safeRow(raw);return contained.ok?ok(contained.value as unknown as ExistingRotation):contained}catch{return fail('database_failure','Rotation state read failed.','$')}};const before=await read();if(!before.ok)return before;if(before.value)return sameRotation(before.value,request,expectedIdentityJcs,replacementIdentityJcs)?ok(deepFreeze({status:'idempotent',rotationId:request.rotationId,previousKeyId:request.expected.keyId,activeKeyId:request.replacement.keyId})):fail('rotation_collision','Rotation identifier has different content.','$.rotationId');
  const auditMetadata=canonicalJsonText({rotationId:request.rotationId,previousKeyId:request.expected.keyId,activeKeyId:request.replacement.keyId,reasonRef:request.reasonRef,issuerRef:request.issuerRef}),statements=[this.db.prepare("INSERT INTO intelligence_key_status_events(environment_id,event_id,key_id,status,effective_at,prior_event_id,reason_ref,issuer_ref) SELECT ?,?,?, 'verify-only',?,?,?,? FROM intelligence_current_key_status WHERE environment_id=? AND key_id=? AND event_id=? AND status='active'").bind(request.environmentId,request.demotionEventId,request.expected.keyId,request.occurredAt,request.expectedStatusEventId,request.reasonRef,request.issuerRef,request.environmentId,request.expected.keyId,request.expectedStatusEventId),this.db.prepare("INSERT INTO intelligence_keys(environment_id,key_id,algorithm,metadata_version,activates_at,created_at,identity_jcs) VALUES(?,?,?,'intelligence-key-metadata/2',?,?,?)").bind(request.environmentId,request.replacement.keyId,request.replacement.algorithm,request.replacement.activatesAt,request.occurredAt,replacementIdentityJcs),this.db.prepare("INSERT INTO intelligence_key_status_events(environment_id,event_id,key_id,status,effective_at,prior_event_id,reason_ref,issuer_ref) VALUES(?,?,?,'active',?,NULL,?,?)").bind(request.environmentId,request.replacementActivationEventId,request.replacement.keyId,request.replacement.activatesAt,request.reasonRef,request.issuerRef),this.db.prepare("INSERT INTO intelligence_audit_events(environment_id,event_id,event_type,record_id,occurred_at,metadata_jcs) VALUES(?,?,'key_rotated',NULL,?,?)").bind(request.environmentId,request.auditEventId,request.occurredAt,auditMetadata),this.db.prepare('INSERT INTO intelligence_key_rotations(environment_id,rotation_id,expected_key_id,expected_algorithm,expected_activates_at,expected_identity_jcs,expected_status_event_id,demotion_event_id,replacement_key_id,replacement_activation_event_id,replacement_algorithm,replacement_activates_at,replacement_identity_jcs,reason_ref,issuer_ref,audit_event_id,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(request.environmentId,request.rotationId,request.expected.keyId,request.expected.algorithm,request.expected.activatesAt,expectedIdentityJcs,request.expectedStatusEventId,request.demotionEventId,request.replacement.keyId,request.replacementActivationEventId,request.replacement.algorithm,request.replacement.activatesAt,replacementIdentityJcs,request.reasonRef,request.issuerRef,request.auditEventId,request.occurredAt)];
  try{const valid=exactMutationResults(await this.db.batch(statements),statements.length);if(!valid.ok)return valid;return ok(deepFreeze({status:'rotated',rotationId:request.rotationId,previousKeyId:request.expected.keyId,activeKeyId:request.replacement.keyId}))}catch{const after=await read();if(after.ok&&after.value)return sameRotation(after.value,request,expectedIdentityJcs,replacementIdentityJcs)?ok(deepFreeze({status:'idempotent',rotationId:request.rotationId,previousKeyId:request.expected.keyId,activeKeyId:request.replacement.keyId})):fail('rotation_collision','Rotation identifier has different content.','$.rotationId');return fail('rotation_conflict','Rotation was stale, contradictory, or rejected.','$')}
 }
 async readAuthoritativeSnapshot(environmentId:string,streamId:string,recordType:string,recordId:string):Promise<DomainResult<AuthoritativeIntelligenceSnapshot>>{
  const args=snapshot({environmentId,streamId,recordType,recordId});if(!args.ok)return fail('invalid_input','Snapshot request is invalid.',args.error.path);let raw:unknown;try{raw=await this.db.prepare(SNAPSHOT_SQL).bind(recordId,environmentId,streamId,recordType).all()}catch{return fail('database_failure','Authoritative snapshot read failed.','$')};const result=safeResults(raw);if(!result.ok)return result;const source=result.value;if(source.length===0)return fail('snapshot_not_found','No authoritative snapshot was found.','$');const records:SnapshotRecord[]=[];let first:Record<string,unknown>|undefined;
  for(const item of source){const row=safeRow(item);if(!row.ok)return row;first??=row.value;const header=parsed(row.value.header_jcs,'$.header_jcs'),payload=parsed(row.value.payload_jcs,'$.payload_jcs'),rights=parsed(row.value.schedule_jcs,'$.schedule_jcs');if(!header.ok)return header;if(!payload.ok)return payload;if(!rights.ok)return rights;const recordSafe=snapshot({...header.value as object,payload:payload.value,contentHash:String(row.value.content_hash),authenticationTag:String(row.value.authentication_tag)});if(!recordSafe.ok)return fail('malformed_envelope','Stored envelope is malformed.','$');records.push({record:recordSafe.value as unknown as AuthenticatedIntelligenceRecord,rightsSchedule:rights.value,retention:{status:String(row.value.retention_status),...(row.value.retention_project_delete_after?{projectDeleteAfter:String(row.value.retention_project_delete_after)}:{}),...(row.value.retention_hard_source_delete_after?{hardSourceDeleteAfter:String(row.value.retention_hard_source_delete_after)}:{})},keyMetadata:{algorithm:String(row.value.key_algorithm),status:String(row.value.key_status),activatesAt:String(row.value.key_activates_at),statusEffectiveAt:String(row.value.key_status_effective_at)},parents:row.value.parent_id?[String(row.value.parent_id)]:[]})}
  const ids=new Set(records.map(x=>x.record.recordId));for(const item of records)for(const parentId of item.parents)if(!ids.has(parentId))return fail('parent_missing','Snapshot omits required ancestry.','$.records');return ok(deepFreeze({version:'authoritative-intelligence-snapshot/1',snapshotId:`head:${String(first?.current_record_id)}:revision:${String(first?.revision)}`,environmentId,streamId,recordType,selectedRecordId:recordId,currentHeadId:String(first?.current_record_id),headRevision:Number(first?.revision),records}))
 }
}
