import type { JsonRecord, JsonValue } from './untrusted-json.ts';
import { SHA256_PATTERN, deepFreeze, fail, identifier, isRecord, ok, record, reference, shape, snapshot, timestamp, type DomainResult } from './domain-validation.ts';

export const DEDUPLICATION_POLICY = Object.freeze({ id: 'append-only-observation-deduplication', version: '2' } as const);
export const OBSERVATION_SCOPE_VERSION = 'observation-identity-scope-v1';
export const MAX_OBSERVATION_FACTS = 16, MAX_SCOPE_OUTCOMES = 16, MAX_CORRECTION_CHAIN_DEPTH = 16;
export interface ObservationIdentityScope { readonly contractVersion: typeof OBSERVATION_SCOPE_VERSION; readonly sportId: `sport:${string}`; readonly competitionId: `competition:${string}`; readonly eventId: `event:${string}`; readonly marketId: string; readonly outcomeIds: readonly string[]; readonly identityContractVersion: string }
export interface ObservationFact { readonly contractVersion: 'observation-fact-v2'; readonly observationRef: string; readonly sourceEnvelopeRef: string; readonly sourceId: string; readonly providerRef: string; readonly scope: ObservationIdentityScope; readonly payloadHash: string; readonly observedAt: string; readonly receivedAt: string; readonly sourceSequence?: string; readonly correctsObservationRef?: string }
export interface OrderingDecision { readonly firstObservationRef: string; readonly secondObservationRef: string; readonly order: 'first_before_second' | 'second_before_first' | 'equal'; readonly primaryKey: 'source_sequence' | 'observed_at' | 'received_at' | 'observation_ref'; readonly sequenceTimestampDisagreement: boolean; readonly policy: typeof DEDUPLICATION_POLICY }
export interface DeduplicationDecision { readonly contractVersion: 'observation-deduplication-v2'; readonly classification: 'new' | 'exact_duplicate' | 'correction' | 'conflict' | 'already_superseded'; readonly reason: string; readonly incomingObservationRef: string; readonly parentObservationRef?: string; readonly matchedObservationRefs: readonly string[]; readonly correctionChain: readonly string[]; readonly ordering?: OrderingDecision; readonly policy: typeof DEDUPLICATION_POLICY; readonly evidenceRefs: readonly string[] }

function tagged(value: JsonValue | undefined, type: 'sport' | 'competition' | 'event', path: string): DomainResult<`${typeof type}:${string}`> { const parsed = identifier(value, path); if (!parsed.ok) return parsed; return parsed.value.startsWith(`${type}:`) && parsed.value.length > type.length + 1 ? ok(parsed.value as `${typeof type}:${string}`) : fail('invalid_entity_id', `ID must use ${type}:<opaque> tag.`, path); }
function optionalRef(value: JsonValue | undefined, path: string): DomainResult<string | undefined> { return value === undefined ? ok(undefined) : reference(value, path); }
function parseScope(value: JsonValue | undefined, path: string): DomainResult<ObservationIdentityScope> { const parsed = record(value, path); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['contractVersion', 'sportId', 'competitionId', 'eventId', 'marketId', 'outcomeIds', 'identityContractVersion'], path); if (!exact.ok) return exact; if (parsed.value.contractVersion !== OBSERVATION_SCOPE_VERSION) return fail('unsupported_version', 'Observation scope version is unsupported.', `${path}.contractVersion`); const sportId = tagged(parsed.value.sportId, 'sport', `${path}.sportId`); if (!sportId.ok) return sportId; const competitionId = tagged(parsed.value.competitionId, 'competition', `${path}.competitionId`); if (!competitionId.ok) return competitionId; const eventId = tagged(parsed.value.eventId, 'event', `${path}.eventId`); if (!eventId.ok) return eventId; const marketId = identifier(parsed.value.marketId, `${path}.marketId`); if (!marketId.ok) return marketId; const identityVersion = reference(parsed.value.identityContractVersion, `${path}.identityContractVersion`, 128); if (!identityVersion.ok) return identityVersion;
  if (!Array.isArray(parsed.value.outcomeIds)) return fail('invalid_input', 'Outcome IDs must be an array.', `${path}.outcomeIds`); if (parsed.value.outcomeIds.length < 2 || parsed.value.outcomeIds.length > MAX_SCOPE_OUTCOMES) return fail('limit_exceeded', `Outcome scope requires 2-${MAX_SCOPE_OUTCOMES} IDs.`, `${path}.outcomeIds`); const outcomeIds: string[] = [], seen = new Set<string>(); for (let index = 0; index < parsed.value.outcomeIds.length; index += 1) { const item = identifier(parsed.value.outcomeIds[index], `${path}.outcomeIds[${index}]`); if (!item.ok) return item; if (seen.has(item.value)) return fail('duplicate_outcome', 'Outcome IDs must be unique.', `${path}.outcomeIds[${index}]`, { inputIndex: index }); if (index && outcomeIds[index - 1] >= item.value) return fail('noncanonical_outcome_order', 'Outcome IDs must be strictly lexicographically ordered.', `${path}.outcomeIds[${index}]`, { inputIndex: index }); seen.add(item.value); outcomeIds.push(item.value); }
  return ok({ contractVersion: OBSERVATION_SCOPE_VERSION, sportId: sportId.value as `sport:${string}`, competitionId: competitionId.value as `competition:${string}`, eventId: eventId.value as `event:${string}`, marketId: marketId.value, outcomeIds, identityContractVersion: identityVersion.value }); }
function fact(value: JsonValue | undefined, path: string): DomainResult<ObservationFact> { const parsed = record(value, path); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['contractVersion', 'observationRef', 'sourceEnvelopeRef', 'sourceId', 'providerRef', 'scope', 'payloadHash', 'observedAt', 'receivedAt', 'sourceSequence', 'correctsObservationRef'], path); if (!exact.ok) return exact; if (parsed.value.contractVersion !== 'observation-fact-v2') return fail('unsupported_version', 'Observation fact version is unsupported.', `${path}.contractVersion`); const observationRef = reference(parsed.value.observationRef, `${path}.observationRef`); if (!observationRef.ok) return observationRef; const sourceEnvelopeRef = reference(parsed.value.sourceEnvelopeRef, `${path}.sourceEnvelopeRef`); if (!sourceEnvelopeRef.ok) return sourceEnvelopeRef; const sourceId = identifier(parsed.value.sourceId, `${path}.sourceId`); if (!sourceId.ok) return sourceId; const providerRef = reference(parsed.value.providerRef, `${path}.providerRef`); if (!providerRef.ok) return providerRef; const scope = parseScope(parsed.value.scope, `${path}.scope`); if (!scope.ok) return scope; if (typeof parsed.value.payloadHash !== 'string' || !SHA256_PATTERN.test(parsed.value.payloadHash)) return fail('invalid_hash', 'Payload hash must be canonical lowercase SHA-256.', `${path}.payloadHash`); const observedAt = timestamp(parsed.value.observedAt, `${path}.observedAt`); if (!observedAt.ok) return observedAt; const receivedAt = timestamp(parsed.value.receivedAt, `${path}.receivedAt`); if (!receivedAt.ok) return receivedAt; if (receivedAt.value.milliseconds < observedAt.value.milliseconds) return fail('invalid_time_order', 'Receipt cannot precede observation.', `${path}.receivedAt`); const sourceSequence = optionalRef(parsed.value.sourceSequence, `${path}.sourceSequence`); if (!sourceSequence.ok) return sourceSequence; const corrects = optionalRef(parsed.value.correctsObservationRef, `${path}.correctsObservationRef`); if (!corrects.ok) return corrects; if (corrects.value === observationRef.value) return fail('correction_cycle', 'Observation cannot correct itself.', `${path}.correctsObservationRef`); return ok({ contractVersion: 'observation-fact-v2', observationRef: observationRef.value, sourceEnvelopeRef: sourceEnvelopeRef.value, sourceId: sourceId.value, providerRef: providerRef.value, scope: scope.value, payloadHash: parsed.value.payloadHash, observedAt: observedAt.value.canonical, receivedAt: receivedAt.value.canonical, ...(sourceSequence.value ? { sourceSequence: sourceSequence.value } : {}), ...(corrects.value ? { correctsObservationRef: corrects.value } : {}) }); }

function numeric(value: string | undefined): bigint | undefined { return value !== undefined && /^(?:0|[1-9]\d{0,38})$/.test(value) ? BigInt(value) : undefined; }
function sign(value: number | bigint): -1 | 0 | 1 { return value < 0 ? -1 : value > 0 ? 1 : 0; }
function compareText(a: string, b: string): -1 | 0 | 1 { return a < b ? -1 : a > b ? 1 : 0; }
function compareTrusted(first: ObservationFact, second: ObservationFact): OrderingDecision { const fs = numeric(first.sourceSequence), ss = numeric(second.sourceSequence), observed = compareText(first.observedAt, second.observedAt); let comparison: -1 | 0 | 1, primaryKey: OrderingDecision['primaryKey']; if (fs !== undefined && ss !== undefined && fs !== ss) { comparison = sign(fs - ss); primaryKey = 'source_sequence'; } else if (observed) { comparison = observed; primaryKey = 'observed_at'; } else { const received = compareText(first.receivedAt, second.receivedAt); if (received) { comparison = received; primaryKey = 'received_at'; } else { comparison = compareText(first.observationRef, second.observationRef); primaryKey = 'observation_ref'; } } const sequence = fs !== undefined && ss !== undefined ? sign(fs - ss) : 0; return deepFreeze({ firstObservationRef: first.observationRef, secondObservationRef: second.observationRef, order: comparison < 0 ? 'first_before_second' : comparison > 0 ? 'second_before_first' : 'equal', primaryKey, sequenceTimestampDisagreement: sequence !== 0 && observed !== 0 && sequence !== observed, policy: DEDUPLICATION_POLICY }); }
export function compareObservationOrder(input: unknown): DomainResult<OrderingDecision> { const safe = snapshot(input); if (!safe.ok) return safe; const parsed = record(safe.value, '$'); if (!parsed.ok) return parsed; const exact = shape(parsed.value, ['first', 'second'], '$'); if (!exact.ok) return exact; const first = fact(parsed.value.first, '$.first'); if (!first.ok) return first; const second = fact(parsed.value.second, '$.second'); if (!second.ok) return second; return ok(compareTrusted(first.value, second.value)); }

function sameScope(a: ObservationFact, b: ObservationFact): boolean { return a.sourceId === b.sourceId && a.providerRef === b.providerRef && JSON.stringify(a.scope) === JSON.stringify(b.scope); }
function sameExactFact(a: ObservationFact, b: ObservationFact): boolean { return sameScope(a, b) && a.sourceEnvelopeRef === b.sourceEnvelopeRef && a.payloadHash === b.payloadHash && a.observedAt === b.observedAt && a.receivedAt === b.receivedAt && a.sourceSequence === b.sourceSequence && a.correctsObservationRef === b.correctsObservationRef; }
function isPolicy(value: JsonValue | undefined): value is JsonRecord { return isRecord(value) && Object.keys(value).length === 2 && value.id === DEDUPLICATION_POLICY.id && value.version === DEDUPLICATION_POLICY.version; }
function validateExisting(existing: readonly ObservationFact[]): DomainResult<ReadonlyMap<string, ObservationFact>> { const byRef = new Map<string, ObservationFact>(), childByParent = new Map<string, string>(); for (let index = 0; index < existing.length; index += 1) { const item = existing[index]; if (byRef.has(item.observationRef)) return fail('duplicate_reference', 'Existing fact references must be unique.', `$.existing[${index}].observationRef`, { inputIndex: index }); byRef.set(item.observationRef, item); }
  for (const item of existing) if (item.correctsObservationRef) { const parent = byRef.get(item.correctsObservationRef); if (!parent) return fail('missing_parent', 'Existing correction parent is missing.', '$.existing', { entityRef: item.correctsObservationRef }); if (childByParent.has(parent.observationRef)) return fail('correction_fork', 'Existing correction graph contains multiple successors.', '$.existing', { entityRef: parent.observationRef }); childByParent.set(parent.observationRef, item.observationRef); if (!sameScope(parent, item)) return fail('correction_scope_conflict', 'Existing correction crosses immutable scope.', '$.existing', { entityRef: item.observationRef }); if (parent.payloadHash === item.payloadHash) return fail('contradictory_supersession', 'Existing correction does not change payload.', '$.existing', { entityRef: item.observationRef }); }
  for (const item of existing) { const seen = new Set<string>(); let cursor: ObservationFact | undefined = item, depth = 0; while (cursor) { if (seen.has(cursor.observationRef)) return fail('correction_cycle', 'Existing correction graph contains a cycle.', '$.existing', { entityRef: cursor.observationRef }); seen.add(cursor.observationRef); cursor = cursor.correctsObservationRef ? byRef.get(cursor.correctsObservationRef) : undefined; if (++depth > MAX_CORRECTION_CHAIN_DEPTH) return fail('correction_chain_limit_exceeded', 'Existing correction chain exceeds limit.', '$.existing'); } }
  return ok(byRef); }
function decision(classification: DeduplicationDecision['classification'], reason: string, incoming: ObservationFact, detail: Partial<DeduplicationDecision> = {}): DomainResult<DeduplicationDecision> { return ok({ contractVersion: 'observation-deduplication-v2', classification, reason, incomingObservationRef: incoming.observationRef, matchedObservationRefs: detail.matchedObservationRefs ?? [], correctionChain: detail.correctionChain ?? [], policy: DEDUPLICATION_POLICY, evidenceRefs: detail.evidenceRefs ?? [incoming.sourceEnvelopeRef], ...(detail.parentObservationRef ? { parentObservationRef: detail.parentObservationRef } : {}), ...(detail.ordering ? { ordering: detail.ordering } : {}) }); }

export function classifyObservation(input: unknown): DomainResult<DeduplicationDecision> { const safe = snapshot(input); if (!safe.ok) return safe; const root = record(safe.value, '$'); if (!root.ok) return root; const exact = shape(root.value, ['incoming', 'existing', 'policy'], '$'); if (!exact.ok) return exact; if (!isPolicy(root.value.policy)) return fail('unsupported_policy', 'Only deduplication policy v2 is supported.', '$.policy'); const incoming = fact(root.value.incoming, '$.incoming'); if (!incoming.ok) return incoming; if (!Array.isArray(root.value.existing)) return fail('invalid_input', 'Existing facts must be an array.', '$.existing'); if (root.value.existing.length > MAX_OBSERVATION_FACTS) return fail('limit_exceeded', 'Existing fact limit exceeded.', '$.existing'); const existing: ObservationFact[] = []; for (let index = 0; index < root.value.existing.length; index += 1) { const item = fact(root.value.existing[index], `$.existing[${index}]`); if (!item.ok) return item; existing.push(item.value); } const graph = validateExisting(existing); if (!graph.ok) return graph; const byRef = graph.value;
  const sameRef = byRef.get(incoming.value.observationRef); if (sameRef) return sameExactFact(sameRef, incoming.value) ? decision('exact_duplicate', 'same_reference_and_complete_fact_tuple', incoming.value, { matchedObservationRefs: [sameRef.observationRef], evidenceRefs: [sameRef.sourceEnvelopeRef] }) : decision('conflict', 'observation_reference_reused', incoming.value, { matchedObservationRefs: [sameRef.observationRef], evidenceRefs: [sameRef.sourceEnvelopeRef, incoming.value.sourceEnvelopeRef] });
  const hashMatches = existing.filter((item) => item.payloadHash === incoming.value.payloadHash); const duplicate = hashMatches.find((item) => sameExactFact({ ...incoming.value, observationRef: item.observationRef }, item)); if (duplicate) return decision('exact_duplicate', 'complete_fact_identity_tuple_matches', incoming.value, { matchedObservationRefs: [duplicate.observationRef], evidenceRefs: [duplicate.sourceEnvelopeRef] }); if (hashMatches.length) return decision('conflict', 'equal_hash_with_different_fact_tuple', incoming.value, { matchedObservationRefs: hashMatches.map((item) => item.observationRef).sort(), evidenceRefs: [...hashMatches.map((item) => item.sourceEnvelopeRef), incoming.value.sourceEnvelopeRef].sort() });
  if (!incoming.value.correctsObservationRef) return decision('new', 'no_duplicate_or_explicit_parent', incoming.value); const parent = byRef.get(incoming.value.correctsObservationRef); if (!parent) return fail('missing_parent', 'Incoming correction parent is missing.', '$.incoming.correctsObservationRef', { entityRef: incoming.value.correctsObservationRef }); if (!sameScope(parent, incoming.value)) return decision('conflict', 'correction_crosses_immutable_scope', incoming.value, { parentObservationRef: parent.observationRef, matchedObservationRefs: [parent.observationRef], evidenceRefs: [parent.sourceEnvelopeRef, incoming.value.sourceEnvelopeRef] }); if (parent.payloadHash === incoming.value.payloadHash) return decision('conflict', 'correction_does_not_change_payload', incoming.value, { parentObservationRef: parent.observationRef, matchedObservationRefs: [parent.observationRef] }); const child = existing.find((item) => item.correctsObservationRef === parent.observationRef); if (child) return decision('already_superseded', 'parent_already_has_successor', incoming.value, { parentObservationRef: parent.observationRef, matchedObservationRefs: [child.observationRef], evidenceRefs: [child.sourceEnvelopeRef, incoming.value.sourceEnvelopeRef] }); const chain = [incoming.value.observationRef]; let cursor: ObservationFact | undefined = parent; while (cursor) { chain.push(cursor.observationRef); cursor = cursor.correctsObservationRef ? byRef.get(cursor.correctsObservationRef) : undefined; } if (chain.length > MAX_CORRECTION_CHAIN_DEPTH) return fail('correction_chain_limit_exceeded', 'Incoming correction would exceed chain limit.', '$.incoming.correctsObservationRef'); return decision('correction', 'explicit_valid_append_only_correction', incoming.value, { parentObservationRef: parent.observationRef, matchedObservationRefs: [parent.observationRef], correctionChain: chain, ordering: compareTrusted(parent, incoming.value), evidenceRefs: chain.map((ref) => (ref === incoming.value.observationRef ? incoming.value : byRef.get(ref)!).sourceEnvelopeRef) }); }
